### ISSUE TITLE
fail fast capability

### ISSUE THREAD

**Issue by ruslander** [jhalterman/failsafe#102]
Hi,

I'm a big fan of this marvel of engineering. Recently integrating with a 3d party we detected
that some requests run to long. The first go to was to see the documentation for FailSafe. Unfortunately no luck. Below is an example of use case we want to have.

```java

    @Test
    public void the_duration_of_the_test_is_10ms() throws Exception {
         CircuitBreaker breaker = new CircuitBreaker()
                .withTimeout(10, TimeUnit.MILLISECONDS);

        Failsafe.with(breaker)
        .get(() -> {
            Thread.sleep(20000); // emulate the long running task
            return 0;
        });
    }
```

I expected `withTimeout` to help me here to cut the execution with a failure at 10ms.
Is this something you guys have on the radar ? Or any work around will be appreciated

Thank you

**Comment by jhalterman** [comment]
@ruslander Thanks for the nice words.

[Setting a timeout](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/CircuitBreaker.html#withTimeout-long-java.util.concurrent.TimeUnit-) does not cause Failsafe to interrupt executions, but instead causes it to mark executions as failed after they naturally complete. In this case, the execution would be marked as failed and would cause the CircuitBreaker to open (after 20 seconds).

The reason that Failsafe doesn't actively interrupt or cancel executions, at least right now, is that interrupting executions would require Failsafe to create a separate timer/thread and could have unexpected side effects - such as if a user's code is not specifically designed to be interrupted.

If you have any thoughts or opinions on this stuff, feel free to share them.

**Comment by ruslander** [comment]
@jhalterman  thank you for quick reply. Here is what came up for now. Sharing it here maybe other people can find it useful or take it from here and push it forward.

```java

public class FailFastPolicyTest {

    ExecutorService executorService = Executors.newCachedThreadPool();

    @Test
    public void fail_fast_policy_applied() throws Throwable {
        CircuitBreaker breaker = new CircuitBreaker();

        try {
            Failsafe.with(breaker)
                    .get(failFastPolicy(10, () -> {
                        Thread.sleep(20000);
                        return 0;
                    }));
        } catch (InternalServerErrorException e) {
        }

        assertTrue(breaker.isOpen());
    }

    @Test
    public void fast_succeeding() throws Throwable {
        Object result = failFastPolicy(3000, () -> new Object());
        assertNotNull(result);
    }

    @Test
    public void propagates_internal_exception() throws Throwable {

        Callable<Object> throwsEx = () -> {
            throw new InternalServerErrorException("This is an emulated exception");
        };

        try {
            failFastPolicy(1000, throwsEx);
        } catch (InternalServerErrorException e) {
            assertThat(e)
                    .isInstanceOf(InternalServerErrorException.class)
                    .hasMessage("This is an emulated exception");
        }
    }

    @Test
    public void when_threshold_exceeded_throws_internal_error() throws Throwable {

        Callable<Object> longRunningExecution = () -> {
            Thread.sleep(10000);
            return new Object();
        };

        try {
            failFastPolicy(100, longRunningExecution);
        } catch (InternalServerErrorException e) {
            assertThat(e)
                    .isInstanceOf(InternalServerErrorException.class)
                    .hasMessage("Execution aborted, exceeded allowed 100 threshold");
        }
    }
    
    private Callable<Object> failFastPolicy(long thresholdMilliseconds, Callable<Object> callable) throws Throwable{
        return ()-> {
            try {
                Future<Object> task = executorService.submit(callable);
                return task.get(thresholdMilliseconds, TimeUnit.MILLISECONDS);
            } catch (ExecutionException e) {
                throw new InternalServerErrorException("Internal exception ", e.getCause());
            } catch (TimeoutException e) {
                throw new InternalServerErrorException("Execution aborted, exceeded allowed " + thresholdMilliseconds + " threshold");
            }
        };
    }
}

```

**Comment by wezell** [comment]
@ruslander thanks for the code, it is working as expected.  I got caught by this too.  The code below seems like it should fail or at least return false but doesn't.  `value==true`, even withFallBack.  Should the fallback be returned if the timeout threshold is exceeded?

```
	private void testFallback()  {
		CircuitBreaker breaker = new CircuitBreaker().withTimeout(1000, TimeUnit.MILLISECONDS);
		boolean value = Failsafe
			.with(breaker)
			.withFallback(false)
			.get(() -> { 
				Thread.sleep(2000);
			    return true;
			});

		assert(value);
	}
```

**Comment by jhalterman** [comment]
@wezell Right now the fallback feature is basically only used for executions that are considered a failure according to a RetryPolicy. This goes for the Failsafe event listeners as well (onFailure, etc.) We may want to extend these to work with failures according to a CircuitBreaker, but there may be some pitfalls to consider. Opened #113. Comments welcome.

**Comment by jhalterman** [comment]
A new `Timeout` policy has been merged which supports failing an execution, and optionally interrupting or cancelling it:

https://github.com/jhalterman/failsafe#timeouts
