### ISSUE TITLE
Retry partial failures

### ISSUE THREAD

**Issue by behrangsa** [jhalterman/failsafe#105]
Hi,

Some AWS APIs can complete with partial success. For example, when calling a `PutRecords` request with 500 entries, it is possible for some of the records to successfully get put and some fail.

```java
PutRecordsRequest request = new PutRecordsRequest();
// add 500 entries to the request
PutRecordsResult response = producer.putRecords(request);
// response.getFailedRecordCount() could be between 0 and 500
// For example, the first 300 records might get inserts and the last 200 fail due to exceeding throughput 
```

In such cases: 

1. the client should wait a bit, 
2. retrieve the index of failed records from `response` and fetch those failed records to build a new `request`
3. re-call `producer.putRecords` with the new request

So every invocation needs access to the result of the previous execution (or `null` for the first execution).

Is this possible to do with failsafe? From what I can see invocations do not have access to results of previous attempts.

**Comment by jhalterman** [comment]
Hi @behrangsa,

This is an interesting use case. Short answer is, not possible right now.

Right now, execution methods such as `run`, `get` and `future` can receive an [ExecutionContext](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/ExecutionContext.html) instance that provides info about previous executions, but it does not currently include the lastFailure. I'm open to adding this, I just haven't had a use case for it so far.

Would something like that work?

**Comment by behrangsa** [comment]
Hi @jhalterman,

Adding `lastFailure` to the `ExecutionContext` would be great. In the meantime I have to reread the docs and see if I can implement a workaround using `onFailedAttempt`. :)

Cheers!

**Comment by whiskeysierra** [comment]
Interesting use case, but I wouldn't push this state down into Failsafe. Keeping track of things like this is best done by the application itself.

**Comment by jhalterman** [comment]
I'd be interested to know if anyone has ideas for how Failsafe could help with this use case. What might an example Failsafe usage with a hypothetical API look like?

**Comment by behrangsa** [comment]
It is generic enough so I guess it will allow us implement retry logic for many additional scenarios -- it at least is enough for the AWS API example.

**Comment by whiskeysierra** [comment]
One way how this could be generalized is to look at it like a `reduce` or left fold. Basically each iteration will feed in left over to the next one and so forth. Reducing the list of open tasks down to zero.

From an API perspective what would be nice is to offer the ability to provide a similar interface like [Stream.reduce](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#reduce-T-java.util.function.BinaryOperator-) so that applications can express their partial retries without binding themselves to failsafe to strongly.

```java
// returns an empty list in this case
failsafe.get(putRecordsRequestEntries, this::putRecords);
```

**Comment by jhalterman** [comment]
> From an API perspective what would be nice is to offer the ability to provide a similar interface like Stream.reduce

Interesting idea. Can you share an example of what that would look like being used vs doing something similar without that kind of API?

**Comment by whiskeysierra** [comment]
Now that I'm looking at your example using the current API it's actually not that bad. With Java 11 and commons-lang/guava you might be able to shorten it a bit:

```java
RetryPolicy<List<String>> retryPolicy = new RetryPolicy<List<String>>()
       .handleResultIf(not(List::isEmpty));

List<String> unsuccessfulRequestEntries = Failsafe.with(retryPolicy).get(context -> 
    return putRecords(firstNonNull(context.getLastResult(), original);
);
```

**Comment by whiskeysierra** [comment]
Looks reasonably easy to me, to be honest.

**Comment by jhalterman** [comment]
With the addition of `ExecutionContext.getLastResult` and `getLastFailure` I'm going to consider this closed. Feel free to comment and/or reopen if you feel those are inadequate for your use case.
