### ISSUE TITLE
Async : How to gracefull shutdown ?

### ISSUE THREAD

**Issue by pgoergler** [jhalterman/failsafe#106]
Hello,

I'm trying FailSafe with:
```java
final ScheduledExecutorService executor = Executors.newScheduledThreadPool(2);
final RetryPolicy retryPolicy = new RetryPolicy()
                .withDelay(100, TimeUnit.MILLISECONDS)
                .retryOn(RuntimeException.class)
                .retryWhen(false)
                ;

// this task will fail 99% of time.
Failsafe
                .with(retryPolicy)
                .with(executor)
                .get((ctx) -> {
                        double i = Math.random();
                        if( i > 0.99 ) {
                            return true;
                        } else if (i < 0.1 ) {
                            throw new RuntimeException(" i = " + i);
                        }
                       return false;
                    })
        ;
```

Then i add a ShutdownHook:
```java
Runtime.getRuntime().addShutdownHook(new Thread(() -> {
       executor.shutdown();
       executor.awaitTermination(1, TimeUnit.HOURS);
}));
```

Is there to do something like:
```java
FailSafe.awaitAllTaskComplete();
executor.shutdown();
executor.awaitTermination(1, TimeUnit.HOURS);
```

Or should i have to store all future created and check if they all have been complete ?

**Comment by jhalterman** [comment]
You'll need to store the futures yourself, else you can interrupt running threads via `executor.shutdownNow()`.

**Comment by ben-manes** [comment]
I implemented a scheduler using `CompletableFuture.delayedExecutor` (Java 9+). That uses an underlying, shared `ScheduledExecutorService` with a JVM-owned thread.

**Comment by jhalterman** [comment]
@ben-manes I don't plan to upgrade Failsafe to Java 9 for a while, but tell me more - how does it allow graceful shutdown?

**Comment by ben-manes** [comment]
In that the scheduler and `ForkJoinPool.commonPool()` are owned by the JVM and cannot be explicitly shutdown, so no shutdown logic is needed in client code.

**Comment by ben-manes** [comment]
commonPool doesn't, but `delayedExecutor` does. They can be used together, e.g.

```java
@Override
public <V> ScheduledFuture<V> schedule(Callable<V> callable, long delay, TimeUnit unit) {
  var executor = CompletableFuture.delayedExecutor(delay, unit, delegate());
  var future = CompletableFuture.supplyAsync(Unchecked.supplier(callable::call), executor);
  return new ScheduledCompletableFuture<>(future, delay, unit);
}
```

But regardless that just means that nothing is needed by Failsafe and users could take advantage of the JVM's shared pools instead, if desired.

**Comment by jhalterman** [comment]
@ben-manes Since you've worked in this area you may know the answer, do you know if it's possible to adapt the common pool to a ScheduledExecutorService, perhaps by having them share the same underlying threadpool? I'm starting to dig but haven't seen a way yet.

**Comment by ben-manes** [comment]
You have to adapt the hidden `ScheduledExecutorService` inside of `CompletableFuture` back to a `ScheduledExecutorService`. The work is delegated to the common pool. Below is my implementation of that (extracted with tests).

```java
public final class CompletableFutures {
  private static final Logger logger = LoggerFactory.getLogger(CompletableFutures.class);

  /**
   * Returns an {@link ScheduledExecutorService} that uses the global scheduler, hidden within
   * {@link CompletableFuture#delayedExecutor}, to delay on. This allows scheduling a task without
   * creating dedicated threads. The tasks are executed on the global
   * {@link ForkJoinPool#commonPool}.
   */
  public static ScheduledExecutorService scheduler() {
    return new Scheduler(ForkJoinPool.commonPool());
  }

  /**
   * Returns an {@link ScheduledExecutorService} that uses the global scheduler, hidden within
   * {@link CompletableFuture#delayedExecutor}, to delay on. This allows scheduling a task without
   * creating dedicated threads. The tasks are executed on the given executor.
   */
  public static ScheduledExecutorService scheduler(ExecutorService executor) {
    return new Scheduler(executor);
  }

  static final class Scheduler extends ForwardingExecutorService
      implements ScheduledExecutorService {
    private final ExecutorService delegate;

    Scheduler(ExecutorService delegate) {
      this.delegate = requireNonNull(delegate);
    }

    @Override
    public ScheduledFuture<?> schedule(Runnable command, long delay, TimeUnit unit) {
      return schedule(Executors.callable(command), delay, unit);
    }

    @Override
    public <V> ScheduledFuture<V> schedule(Callable<V> callable, long delay, TimeUnit unit) {
      var executor = CompletableFuture.delayedExecutor(delay, unit, delegate());
      var future = CompletableFuture.supplyAsync(Unchecked.supplier(callable::call), executor);
      return new ScheduledCompletableFuture<>(future, delay, unit);
    }

    @Override
    public ScheduledFuture<?> scheduleAtFixedRate(Runnable command,
        long initialDelay, long period, TimeUnit unit) {
      var task = FixedRateRunnable.builder()
          .period(Duration.ofNanos(unit.toNanos(period)))
          .scheduler(this)
          .task(command)
          .build();
      var future = schedule(task, initialDelay, unit);
      task.scheduledFuture().set(future);
      return future;
    }

    @Override
    public ScheduledFuture<?> scheduleWithFixedDelay(Runnable command,
        long initialDelay, long delay, TimeUnit unit) {
      var task = FixedDelayRunnable.builder()
          .delay(Duration.ofNanos(unit.toNanos(delay)))
          .scheduler(this)
          .task(command)
          .build();
      var future = schedule(task, initialDelay, unit);
      task.scheduledFuture().set(future);
      return future;
    }

    @Override
    protected ExecutorService delegate() {
      return delegate;
    }
  }

  static final class ScheduledCompletableFuture<V>
      extends ForwardingFuture<V> implements ScheduledFuture<V> {
    private final CompletableFuture<V> delegate;
    private final AtomicBoolean cancelled;
    private final long time;

    ScheduledCompletableFuture(CompletableFuture<V> delegate, long delay, TimeUnit unit) {
      this.time = System.nanoTime() + unit.toNanos(delay);
      this.delegate = requireNonNull(delegate);
      this.cancelled = new AtomicBoolean();
    }

    @Override
    public long getDelay(TimeUnit unit) {
      return unit.convert(time - System.nanoTime(), NANOSECONDS);
    }

    @Override
    public int compareTo(Delayed other) {
      if (other == this) {
        return 0;
      } else if (other instanceof ScheduledCompletableFuture) {
        return Longs.compare(time, ((ScheduledCompletableFuture<?>) other).time);
      }
      return Longs.compare(getDelay(NANOSECONDS), other.getDelay(NANOSECONDS));
    }

    @Override
    public boolean cancel(boolean mayInterruptIfRunning) {
      boolean wasCancelled = cancelled.getAndSet(true);
      super.cancel(mayInterruptIfRunning);
      return !wasCancelled;
    }

    @Override
    public boolean isCancelled() {
      return cancelled.get();
    }

    @Override
    public boolean isDone() {
      return isCancelled() || delegate().isDone();
    }

    @Override
    protected Future<? extends V> delegate() {
      return delegate;
    }
  }

  @AutoValue @AutoBuilder
  static abstract class FixedRateRunnable implements Runnable {
    abstract AtomicReference<ScheduledFuture<?>> scheduledFuture();
    abstract Scheduler scheduler();
    abstract Duration period();
    abstract Runnable task();

    @Override
    @SuppressWarnings("FutureReturnValueIgnored")
    public void run() {
      try {
        var future = scheduledFuture().get();
        if ((future == null) || !future.isCancelled()) {
          long next = System.nanoTime() + period().toNanos();
          task().run();
          long delay = next - System.nanoTime();
          scheduler().schedule(this, delay, TimeUnit.NANOSECONDS);
        }
      } catch (Exception e) {
        logger.warn("Scheduled task with fixed rate failed; not rescheduled ({})",
            task().getClass().getName(), e);
        throw e;
      }
    }

    static CompletableFutures_FixedRateRunnable_Builder builder() {
      return CompletableFutures_FixedRateRunnable_Builder.builder()
          .scheduledFuture(new AtomicReference<>());
    }
  }

  @AutoValue @AutoBuilder
  static abstract class FixedDelayRunnable implements Runnable {
    abstract AtomicReference<ScheduledFuture<?>> scheduledFuture();
    abstract Scheduler scheduler();
    abstract Duration delay();
    abstract Runnable task();

    @Override
    @SuppressWarnings("FutureReturnValueIgnored")
    public void run() {
      try {
        var future = scheduledFuture().get();
        if ((future == null) || !future.isCancelled()) {
          task().run();
          scheduler().schedule(this, delay().toNanos(), TimeUnit.NANOSECONDS);
        }
      } catch (Exception e) {
        logger.warn("Scheduled task with fixed delay failed; not rescheduled ({})",
            task().getClass().getName(), e);
        throw e;
      }
    }

    static CompletableFutures_FixedDelayRunnable_Builder builder() {
      return CompletableFutures_FixedDelayRunnable_Builder.builder()
          .scheduledFuture(new AtomicReference<>());
    }
  }
}
```

```java
@SuppressWarnings("FutureReturnValueIgnored")
public final class CompletableFuturesTest {

  @Test
  public void scheduler_schedule() {
    AtomicBoolean done = new AtomicBoolean();
    Duration delay = Duration.ofMillis(500);
    long startTime = System.nanoTime();
    CompletableFutures.scheduler().schedule(() -> done.set(true),
        delay.toNanos(), TimeUnit.NANOSECONDS);
    await().untilTrue(done);
    assertThat(System.nanoTime() - startTime, greaterThanOrEqualTo(delay.toNanos()));
  }

  @Test
  public void scheduler_scheduleAtFixedRate() throws InterruptedException {
    AtomicInteger done = new AtomicInteger();
    Duration initialDelay = Duration.ofMillis(250);
    Duration period = Duration.ofMillis(500);
    long startTime = System.nanoTime();
    var future = CompletableFutures.scheduler().scheduleAtFixedRate(() -> done.incrementAndGet(),
        initialDelay.toNanos(), period.toNanos(), TimeUnit.NANOSECONDS);
    await().untilAtomic(done, greaterThanOrEqualTo(1));
    assertThat(System.nanoTime() - startTime, greaterThanOrEqualTo(initialDelay.toNanos()));

    await().untilAtomic(done, greaterThanOrEqualTo(2));
    assertThat(System.nanoTime() - startTime, greaterThanOrEqualTo(period.toNanos()));
    future.cancel(false);

    int completed = done.get();
    TimeUnit.NANOSECONDS.sleep(period.toNanos());
    assertThat(done.get(), is(completed));
  }

  @Test
  public void scheduler_scheduleAtFixedDelay() throws InterruptedException {
    AtomicInteger done = new AtomicInteger();
    Duration initialDelay = Duration.ofMillis(250);
    Duration delay = Duration.ofMillis(500);
    long startTime = System.nanoTime();
    var future = CompletableFutures.scheduler().scheduleAtFixedRate(() -> done.incrementAndGet(),
        initialDelay.toNanos(), delay.toNanos(), TimeUnit.NANOSECONDS);
    await().untilAtomic(done, greaterThanOrEqualTo(1));
    assertThat(System.nanoTime() - startTime, greaterThanOrEqualTo(initialDelay.toNanos()));

    await().untilAtomic(done, greaterThanOrEqualTo(2));
    assertThat(System.nanoTime() - startTime, greaterThanOrEqualTo(
        initialDelay.plus(delay).toNanos()));
    future.cancel(false);

    int completed = done.get();
    TimeUnit.NANOSECONDS.sleep(delay.toNanos());
    assertThat(done.get(), is(completed));
  }
```

**Comment by jhalterman** [comment]
@ben-manes Thanks! This is helpful. I had a quick look at CompletableFuture and noticed that it uses an internal ScheduledExecutorService for triggering delayed executions. I may just do the same for my own adaptation 👍

**Comment by ben-manes** [comment]
Exactly. If you can use CompletableFuture's internal ScheduledExecutorService, then you don't have to create your own threads. That way the threads are managed by the JVM, so no uckiness of libraries creating threads or needing clients to shut them down.

**Comment by jhalterman** [comment]
I doubt I'll be able to use CompletableFuture's internal ScheduledExecutorService unless I commit users to Java 9. I could lazily create a static ScheduledExecutorService if users hit any async APIs without providing their own scheduler. In that case, I'd still prefer to have execution done on the common pool rather than spinning up more threads in some pool that Failsafe controls. Think this sounds decent?

**Comment by ben-manes** [comment]
It's not bad. I do have a general dislike of libraries creating their own threads, as it feels heavy-handed. But that's more of a gut feeling and if you keep the option to specify the scheduler, then its probably the right tradeoff.

**Comment by jhalterman** [comment]
Agree - I think bringing your own scheduler would be more common, but in the era of the common pool, not having to bring your own seems nice, and would allow me to unify some of the APIs that currently distinguish between sync and async (where async is only available after you've configured a scheduler).

**Comment by jhalterman** [comment]
Closing for now.

**Comment by ben-manes** [comment]
Not sure if it is helpful, but I used `delayedExecutor` as a scheduler in Caffeine 2.8. This is done via reflection to be JDK8 compatible. Alternatively I could have used a multi-version jar, but that seemed error-prone given how rare it is used. In my case the scheduling is paced at a rate of 1/sec per cache, in order to batch expiration work if possible.

You might consider using the `delayedExecutor` if available instead of your own thread, to be extra friendly to classloader unloading (e.g. Tomcat) for JDK9+ users.

**Comment by jhalterman** [comment]
I ended up doing a scheduler in Failsafe that [delegates](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/util/DelegatingScheduler.java#L30) to the common pool by default. IIRC, this means that threads are automatically terminated on JVM exit, but I'm not sure if that's any different than using your own executor with daemon threads.

**Comment by ben-manes** [comment]
Yes, that part is the same. However you have `ScheduledExecutorService delayer` for the scheduling part. This is what I use `delayedExecutor` for, so that I don't spin up any threads myself.

**Comment by ben-manes** [comment]
[Scheduler](https://github.com/ben-manes/caffeine/blob/fb89d910bc4199ef63b621bb3772d6dcf7d26045/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Scheduler.java#L43) interface, with [SystemScheduler](https://github.com/ben-manes/caffeine/blob/fb89d910bc4199ef63b621bb3772d6dcf7d26045/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Scheduler.java#L101) for Java 9+ users. The `Executor` is passed in, defaulting to `commonPool()` unless `Caffeine.executor(es)` is set.

**Comment by jhalterman** [comment]
So you're suggesting use a bit of reflection to see if JDK 9's delayedExecutor is available, else fallback to the current approach?

**Comment by ben-manes** [comment]
Yes. I think that would be friendlier for use-cases like https://github.com/jhalterman/expiringmap/issues/61. Then only JDK8 users might be impacted by your static thread, which will dwindle over time. Eventually you'll be safe to make a new baseline JDK and remove the reflection.

I'd have suggested method handles, but there was a memory leak ([JDK-8174749](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8174749) in some JDKs.

**Comment by jhalterman** [comment]
Thanks for the suggestion. Opened #197 for this.

**Comment by ben-manes** [comment]
As an aside, if I didn't show you already, you'll probably enjoy reading through my [TimerWheel](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java) code. I have a simple [Pacer](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Pacer.java) to enforce a ~1s delay between executions, since this is a callback to perform routine maintenance on the cache. This lets all expiration work be done in amortized O(1) time. The heap in SES is minimally touched since it only schedules the next event there, managing the cache entries within the timer wheel (if variable) or LRU lists (if fixed).

**Comment by jhalterman** [comment]
Very interesting, and obviously applicable to ExpiringMap (which I haven't had time or need to work on lately, unfortunately) which uses a `ConcurrentSkipListSet` (with the associated costs) for storing entries with variable expiration.
