### ISSUE TITLE
Idea: Offer proxy factory

### ISSUE THREAD

**Issue by fzakaria** [jhalterman/failsafe#107]
I tend to usually wrap clients I have with failsafe retry policy & circuit breaker, but perhaps a nice wholesale solution would be to offer a proxy factory.

```java
/** Proxy class that retries operations and has a circuit breaker. */
protected class FailsafeInvocationHandler<T> extends AbstractInvocationHandler {

  private final T underlying;
  private final RetryPolicy retryPolicy;
  private final CircuitBreaker ciruitBreaker;

  public FailsafeInvocationHandler(T underlying, RetryPolicy retryPolicy, CircuitBreaker circuitBreaker) {
    this.underlying = Preconditions.checkNotNull(underlying);
    this.retryPolicy = Preconditions.checkNotNull(retryPolicy);
    this.circuitBreaker = Preconditions.checkNotNull(circuitBreaker);
  }

  /**
   * Create a Proxy around an underlying interface such that the method calls are wrapped with a
   * {@link RetryPolicy} and a {@link CircuitBreaker}
   */
  public static <T> T retryingProxy(T client, Class<T> clazz) {
    return Reflection.newProxy(clazz, new FailsafeInvocationHandler<>(client));
  }

  @Override
  protected Object handleInvocation(Object proxy, Method method, Object[] args) throws Throwable {
    return invokeWithRetry(underlying, method, args);
  }

  private Object invokeWithRetry(Object target, Method method, Object[] args)
      throws Throwable {
    try {
      return Failsafe.with(circuitBreaker)
          .with(retryPolicy)
          .get(() -> method.invoke(target, args));
    } catch (FailsafeException ex) {
      throw unwrapException(ex); //unwrap FailsafeException and InvocationTargetException
    }
  }
}
```

Then maybe you can have a fluent style factory like

```java
EchoClient client = ....
client = Failsafe.with(RETRY_POLICY).with(CIRCUIT_BREAKER).proxy(client, EchoClient.class);
```

**Comment by Tembrel** [comment]
Neat!

**Comment by jhalterman** [comment]
Hi @fzakaria - 

I had thought about this before. What I'm wondering is how generally useful this is (and for how many people), versus just passing a lambda expression or method reference into Failsafe:

```
FooService fooServiceProxy = Failsafe.with(retryPolicy).proxy(fooService, FooService.class);
fooServiceProxy.makeFoo();
```

vs

```
Failsafe.with(retryPolicy).run(() -> fooService.makeFoo());
```

I suppose it would depend on how heavily one uses Failsafe. Also worth considering is how many use cases would be limited by JDK proxies being interface based. I would probably want to support class based proxies via ByteBuddy or Cglib, but as an optional feature/dependency only since this would increase the distro size by a lot.

So yea - again, just generally wondering how useful this is to them. Input from anyone is welcome.

**Comment by Tembrel** [comment]
Interface-based proxies alone are still useful. The motivating case for me would be that of a service interface, where most of the methods of the interface might need some kind of common Failsafe handling. (The ones that don't won't be harmed by being wrapped unnecessarily.)

It doesn't add much conceptual weight, and the implementation, while straightforward, would be hard to roll on one's own.

So I'm in favor of this limited proxying, before even considering class-based proxies.

**Comment by fzakaria** [comment]
I can just remove the precondition check in the accompanying PullRequest for checking if the `Class<T>` is an interface and instead catch failures to create the Proxy and rethrow a nicer mesage like "You must add support for bytecode proxy factories like bytebuddy or asm".

We found this useful for the same reason @Tembrel mentioned. 
We use Failsafe in conjunction with HTTP/RPC clients where the interface is the RPC definition. Wrapping the full service implementation with support for circuitbreaking / retry has been useful.

**Comment by jhalterman** [comment]
@Tembrel I remember previously [you mentioned](https://github.com/jhalterman/failsafe/issues/80#issuecomment-279235361) that you were concerned that wrapping Failsafe calls into Callables/Runnables would alter their semantics. Also, that offering a `.wrap` feature [would decrease the power to weight ratio](https://github.com/jhalterman/failsafe/issues/80#issuecomment-290998697) of the API. Proxying seems similar though. Any thoughts?

**Comment by Tembrel** [comment]
My objection to the `Callable` wrapper was that it would have enshrined a particular set of choices for how to handle exceptions from the Failsafe framework. One user might have been fine with the choices, but another might not.

In this case, it depends on what the implementation of `unwrapException` is. If it preserves the set of potential exceptions thrown by `underlying`, then the user doesn't have to think about it, and I'm OK with it.

If there's no agreement on what `unwrapException` does, then yes, I have a similar concern as before.

@fzakaria - What did you have in mind for `unwrapException(ex)`?

**Comment by fzakaria** [comment]
@Tembrel feel free to check out the pull-request https://github.com/jhalterman/failsafe/pull/108

Here is the relevant snippet for `unwrapException`

```java
     /**
      * Unwrap the exception that Failsafe throws.
      */
     private static Throwable unwrapException(FailsafeException ex) {
         // There are two possibly layers of indirection here.
         //  1) Fail-safe wraps exceptions with FailsafeException
         //  2) Proxy clients use reflection to invoke methods, which wraps
         //     exceptions in InvocationTargetExceptions.
         Throwable inner = ex.getCause();
         if (inner instanceof InvocationTargetException) {
             inner = inner.getCause();
         }
         return inner;
     }
```

Basically I don't want to expose Failsafe or the fact that the interface is proxied.
This `unwrapException` unwraps the wrapping that Failsafe and Proxy provide.

**Comment by Tembrel** [comment]
This works for me.

**Comment by Tembrel** [comment]
I wrote a comment that said "This works for me", and then I deleted it, because I worry about the case where `FailsafeException` wraps an exception that **isn't** an `InvocationTargetException`. Just rethrowing that exception, if it isn't in the signature of the proxied method, could cause a "sneaky throw" of an undeclared checked exception (I think). Maybe such checked exceptions in that case should be wrapped in something unchecked? Some kind of `Error`, even?

**Comment by fzakaria** [comment]
Are you worried about an error / unexpected case ?

Let's discuss the specifics on the PR if we've agreed enough to move
forward with the idea (proxy creation) ?

**Comment by whiskeysierra** [comment]
In my opinion this proxy factory is best suited to live in a separate library, but within failsafe directly. Maybe someone is willing to start a `failsafe-proxy` repo?

**Comment by jhalterman** [comment]
This thread has been here for a while, but I'm pretty confident that this is most appropriate for a separate library, or at least, a separate Maven module. In that case we'd need to explore how to extend or wrap Failsafe in such a way as to offer proxying.

**Comment by fzakaria** [comment]
Feel free to close the issue and pr if you have no interested in accepting.
The pattern was useful but I'm open to a different avenue to surfacing it to any worthwhile consumer.

**Comment by jhalterman** [comment]
Thanks - along those lines, let me know if there
