### ISSUE TITLE
Why is a ScheduledExecutorService required to retry a function that returns CompletableFuture?

### ISSUE THREAD

**Issue by whiskeysierra** [jhalterman/failsafe#109]
https://github.com/jhalterman/failsafe#completablefuture-integration

Why is that required? Why can't failsafe just call the function again to get another future?
I think I'm missing something obvious here. Can you explain this one real quick?

**Comment by Tembrel** [comment]
In the synchronous setting, everything happens in the current thread, both the retries and the delays between retries. We expect the thread to block while this happens, so we don't worry about thread utilization.

In an asynchronous setting, the retries are happening in potentially different threads, and delays should not waste utilization of shared threads by blocking. Failsafe needs to be given a way to say "asynchronously execute this callable with this delay", which is exactly what ScheduledExecutorService provides.

The end result is that
```java
Failsafe.with(retryPolicy)
    .with(schedExecService)
    .future(() -> someCompletableFuture())
```
itself returns a `CompletableFuture` that represents the result of asynchronously retrying, possibly with delays, the call to `someCompletableFuture()`.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Follow up question: Why does the same apply to circuit breakers? Couldn't
they be done without a scheduler?
