### ISSUE TITLE
best way to listen for failures in CircuitBreaker?

### ISSUE THREAD

**Issue by alexeyOnGitHub** [jhalterman/failsafe#114]
Hi! 
I want to actively listen to what is going on in my CircuitBreaker (success/failure/failure-because-slow rates) and report those metrics/events to my event tracking system (real-time).

I do not see a way to attach a listener for that to CircuitBreaker class. there is some API for that in "retrier" class, but not in CircuitBreaker. 
I guess one way to achieve that could be *extending* CircuitBreaker class and overriding "recordSuccess" and "recordFailure" methods, but maybe there is a simpler way?

what do you guys think about adding these methods to CircuitBreaker class - 

* onFailure(..)
* onSuccess(..)
* onFailureBecauseTooSlow(..)  - I suspect this one cannot be tracked separately from "onFailure" at the moment, but that could be a separate improvement.

?

**Comment by whiskeysierra** [comment]
Sounds related to #113

**Comment by jhalterman** [comment]
Fixed in master:

```java
CircuitBreaker breaker = new CircuitBreaker()
  .onSuccess(e -> log.info(e.result));
  .onFailure(e -> log.warn(e.failure));
```
