### ISSUE TITLE
Setting jitter without a delay works fine

### ISSUE THREAD

**Issue by JanecekPetr** [jhalterman/failsafe#116]
The `withJitter` method says:

> Throws: `IllegalStateException` - if no delay has been configured

but the following works just fine:
```
RetryPolicy retryPolicy = new RetryPolicy()
    .retryOn(IllegalArgumentException.class)
    .withJitter(200, TimeUnit.MILLISECONDS);

Failsafe.with(retryPolicy)
    .run(() -> {
        throw new IllegalArgumentException("nope");
    });
```
because the underlying delay has been initialised to 0 (no delay). There is even code in `withJitter()` that checks the delay, `Assert.state(delay != null, "...")`, but that obviously never triggers.

If #115 is fixed to cap the minimum delay to 0, then this check no longer makes sense, and the documentation should be fixed. If not, the code is simply wrong and does not check what it thinks it checks.

**Comment by jhalterman** [comment]
We should throw IllegalStateException when setting a jitter without a delay.
