### ISSUE TITLE
Cancel execution on Timeout

### ISSUE THREAD

**Issue by celdridge91190** [jhalterman/failsafe#120]
The timeout functionality in CircuitBreaker does not allow you to cancel execution of the task on timeout. I think it would make sense for this to cancel the execution, even if that's optional, to prevent the caller from waiting for execution regardless of whether not a timeout occurs.

**Comment by jhalterman** [comment]
Failsafe 2.2.0 was just released, and includes a proper `Timeout` policy that allows executions to be failed, cancelled and even interrupted if a timeout is exceeded.

https://github.com/jhalterman/failsafe#timeouts
https://github.com/jhalterman/failsafe#execution-cancellation
