### ISSUE TITLE
Retry with max duration doesn't work

### ISSUE THREAD

**Issue by Ityan** [jhalterman/failsafe#121]
code from example successfully finished after 15 seconds

```
Boolean result = Failsafe.with(new RetryPolicy()
		.withMaxRetries(1)
		.withMaxDuration(5, TimeUnit.SECONDS))
		.get(() -> {
			int count = 0;
			while (true) {
				Thread.sleep(1000);
				count++;
				System.out.println(count);
				if (count == 15) break;
			}
			return true;
		});
```

**Comment by Tembrel** [comment]
`maxDuration` of 5 seconds means that Failsafe will not retry if still unsuccessful after 5 seconds. [It will **not** interrupt running computations.](https://github.com/jhalterman/failsafe/blob/031f36276e715302c9a42640bba4f43f1bbff6d8/src/main/java/net/jodah/failsafe/AbstractExecution.java#L131-L139) In your case, the first try succeeds (after 15 seconds), so the `maxDuration` value isn't used.
