### ISSUE TITLE
A favor / question 

### ISSUE THREAD

**Issue by hariraogotit** [jhalterman/failsafe#126]
Hi,

In the below 
     RetryPolicy retryPolicy = new RetryPolicy().retryOn(MyException.class)
                                                   .withDelay(1, TimeUnit.SECONDS)
                                                   .withMaxRetries(3);

        Failsafe.with(retryPolicy).run(() -> connect());

Is there anyway to change the values when retrying again. For example  I am submitting a trade with a trader id. If this trader id is no longer available I throw an exception. I would like to change the trader id next time I try rather than rerunning with the same trader id. So is there any option to intercept in between tries and change the values? Please can someone help?

P.S - Apologies,   I am sure this is not the right place to raise questions but I do not know the appropriate place hence asking the question here

**Comment by jhalterman** [comment]
Failsafe doesn't provide a mechanism for storing and tracking arbitrary information across executions. It does provide a context object though which tracks a few things such as the number of executions:

```java
Failsafe.with(retryPolicy).run((ctx) -> {
  if (ctx.getExecutions() == 0)
    connectToPrimary();
  else
    connectToBackup();
});
```

You can also track some state across executions outside of Failsafe:

```java
AtomicInteger executionCount = new AtomicInteger();
Failsafe.with(retryPolicy).run((ctx) -> {
  if (executionCount.get() == 0) {
    executionCount.incrementAndGet();
    connectToPrimary();
  }  else
    connectToBackup();
});
```

**Comment by hariraogotit** [comment]
@jhalterman - Thank you very much for the quick and useful response.
