### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by huangyunbin** [jhalterman/failsafe#127]
![image](https://user-images.githubusercontent.com/1046037/37746415-1bdf9d54-2db5-11e8-81f9-f92d2d78b598.png)

maybe It is a jdk bug ?  my jdk version is 1.8.0_40

is any way solve this?

**Comment by jhalterman** [comment]
Do you have a stacktrace?

**Comment by jhalterman** [comment]
Looks like this was a javac bug, perhaps with u40:

https://bugs.openjdk.java.net/browse/JDK-8068399

Maybe try a newer JDK?

**Comment by huangyunbin** [comment]
this bug is fixed in  jdk9, change jdk is too troublesome.

i find cause is  this code
![image](https://user-images.githubusercontent.com/1046037/37757300-74f82d84-2de7-11e8-88b1-4636fbdff927.png)

so，i delete AbstractFailsafeTest class three method: shouldFallbackWhenCircuitBreakerIsOpen,shouldFallbackAfterFailureWithCircuitBreaker,shouldFallbackAfterFailureWithRetries.

 it is ok now .

**Comment by jhalterman** [comment]
Ok - yea I don't want to remove test coverage to workaround a JDK bug that appears to only effect certain revisions.
