### ISSUE TITLE
Separate timeout from CircuitBreaker

### ISSUE THREAD

**Issue by BCjmiller** [jhalterman/failsafe#133]
Timeouts should be able to be configured completely independently from CircuitBreakers. Having them intrinsically tied together limits flexibility.

**Comment by jhalterman** [comment]
This has been thought about a bit before. Timeouts in circuit breakers are passive, meaning we don't use them to interrupt execution, but rather to open the circuit breaker if an execution exceeds the timeout. I agree with the idea of using them more generally for any type of execution, but how do you think this should work?

While passive timeouts are fine for circuit breakers, there are two problems with more active timeouts:
- We'd need a separate thread to do something when the timeout is exceed
- The something we do would probably be to try and stop execution, somehow, by interrupting it
  - Interrupting execution only works well if the code being executed is specifically designed to be interrupted

Those are the things that we've thought about when this has come up before. Any thoughts?

**Comment by BCjmiller** [comment]
Yes, it would require some threading shenanigans, for sure.

To that end, I believe that [Hystrix](https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds)'s [`THREAD`](https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy)  approach would be a good pattern to follow - or at the very least, a good place to start from in terms of thinking about an interruptible threaded design.

With regard to the second subpoint: I agree that this'd be giving implementers a lot of rope with which they might end up hanging themselves due to the requirement of designing interrupt-tolerant code, but frankly, having the invoked function interrupted is the entire point of this proposed feature. At the end of the day, I would argue that that's more a matter of making good and thorough documentation.

**Comment by jhalterman** [comment]
A new `Timeout` policy has been merged into master:

https://github.com/jhalterman/failsafe#timeouts
