### ISSUE TITLE
Circuit Breaker standalone mode - question about HalfOpen state

### ISSUE THREAD

**Issue by dmbor** [jhalterman/failsafe#135]
I'm trying to use Circuit breaker in standalone mode and it seems that if I do that the way it's suggested in the docs - HalfOpen state related logic is broken - in particular, limiting of concurrent executions does not work, since in that mode I never construct any execution instance and therefore never increment execution counter in CB.

Could you advise how I could use CB in standalone mode better? so that HalfOpen state works? How I'm using approach from readme here.

Thanks!

**Comment by hazeltroost** [comment]
I came here to report the same bug! Hah.

**Comment by jhalterman** [comment]
Fixed by 41edf0b
