### ISSUE TITLE
Behaviour of withFallback - should it always be executed regardless of the threshold values?

### ISSUE THREAD

**Issue by stratful** [jhalterman/failsafe#138]
Hi,

This is more of a question/query, than necessarily an issue, but I would like some clarification of the hierarchy of the behaviour with regard to the fallback method.

Is it correct that it is always executed regardless of the threshold values?

Example being - if the first request sent to the code fails, the circuit will still be closed but the fallback is still executed. That is what is happening in my implementation. See below.

I was not sure if the fallback should only kick in when the circuit is open. Is it possible for that to be achieved, as that is ideally what i would like to happen. Example being, first 10 reqs fails and client is returned an error and then the fallback kicks in when the circuit is open.

Code snippet is below

   CIRCUIT_BREAKER = new CircuitBreaker();
        CIRCUIT_BREAKER.withDelay(1, TimeUnit.MINUTES); 
        CIRCUIT_BREAKER.withFailureThreshold(10); 
        CIRCUIT_BREAKER.withSuccessThreshold(5); 

        // open circuit when this specific exception is thrown by vayant.
        CIRCUIT_BREAKER.failIf(new BiPredicate<GetCalendarAndFlightAvailabilityResponse, Throwable>() {
            @Override
            public boolean test(GetCalendarAndFlightAvailabilityResponse response, Throwable throwable) {
                return throwable instanceof UnexpectedException && ((UnexpectedException) throwable).getErrorCode().equals(
                        ERROR_CODE_TO_FAIL_ON);
            }
        });

            response = Failsafe.with(CIRCUIT_BREAKER).withFallback(new CheckedFunction<Exception, Object>() {
                @Override
                public GetCalendarAndFlightAvailabilityResponse apply(Exception e)  {
                         return x.getCalendarAndFlightAvailability(request);
                 }

            }).get(new Callable<GetCalendarAndFlightAvailabilityResponse>() {
                @Override
                public GetCalendarAndFlightAvailabilityResponse call() {
                    return x.getCalendarAndFlightAvailability(request);
                }
            });

**Comment by jhalterman** [comment]
As of 2.0, `Fallback` is a `Policy` implementation (same as `RetryPolicy` and `CircuitBreaker`). Each Policy declares its own failure conditions and makes its own determination about whether an execution result is a failure. Ex:

```java
Fallback fallback = new Fallback.of(this::connectToBackup).handle(ConnectException.class);
CircuitBreaker circuitBreaker = new CircuitBreaker().handle(Exception.class);

Failsafe.with(fallback, circuitBreaker).get(this::connect);
```


This should clarify and simplify things going forward.
