### ISSUE TITLE
Retry based on result, e.g. HTTP status 404 during webservice call

### ISSUE THREAD

**Issue by jansohn** [jhalterman/failsafe#142]
Is it possible to retry based on the actual return value? I want for example to retry if my returned response object contains an HTTP status of 404.

    Response responseEntity = Failsafe.with(retryPolicy)
        .onFailedAttempt(ex -> log.warn("HTTP POST ({}) failed: '{}'", webTarget.getUri(), ex.getMessage()))
        // fail if responseEntity.getStatus() == 404
        .get(() -> webTarget.request().post(Entity.entity(form, MediaType.APPLICATION_FORM_URLENCODED_TYPE)));
    
    int status = responseEntity.getStatus(); // might be 404

**Comment by whiskeysierra** [comment]
That's what retryIf(Predicate) is for

**Comment by jansohn** [comment]
Can you give me an example? I suppose I need to cast the object somehow?

**Comment by billoneil** [comment]
```java
new RetryPolicy()
    .retryIf((Response response) -> {
        if (!response.isSuccessful()) {
            // Close the body if its not successful
            response.close();
            return true;
        }
        return false;
    })
    .withBackoff(500, 5000, TimeUnit.MILLISECONDS)
    .withMaxRetries(3);
```

**Comment by jansohn** [comment]
Thanks, works like a charm!
