### ISSUE TITLE
withFallback does not respect failOn/failIf

### ISSUE THREAD

**Issue by hazeltroost** [jhalterman/failsafe#144]
No matter what exceptions the circuit breaker has been told to fail/not fail on, if an exception is thrown the fallback will always execute. 

No matter what predicates have been configured, the fallback will not execute if an exception was not thrown.

**Comment by jhalterman** [comment]
This should be resolved in master. Fallback is not a `Policy`, and all `Policy` implementations can register their own `handle`/`handleIf`/`handleResult`, etc., conditions.
