### ISSUE TITLE
Howto retry out-of-order

### ISSUE THREAD

**Issue by yegodm** [jhalterman/failsafe#151]
Say, I am polling a database object to get into a particular state. At the same time an external event may come informing that the state has changed. It would be beneficial to cause OOO-retry to occur now to avoid the delay until the next retry. Is it possible to force an out-of-order retry before the next scheduled one occurs? If it is, what is the right way to do that?

**Comment by jhalterman** [comment]
There is not, really. I'd be interested to know if you have any suggestion for how this should work, in terms of the API, if you were to tweak the current API.

**Comment by jhalterman** [comment]
Closing for now. Feel free to open with some example of how this might look in the API.
