### ISSUE TITLE
[DISCUSS] Failure policy composition

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#153]
As part of #21 I'd like to add support for arbitrarily composing policies. One question this raises is the order in which we should declare policies: inner-most first or outer-most first.

For example, let's say we want a failure to first go through a CircuitBreaker, then retries, then a fallback. We could declare these in the order they're applied to an execution result:

```java
// Inner-most policy first
Failsafe.
  .with(circuitbreaker)
  .with(retries)
  .with(fallback)
  .get(() -> true)
```

or if we think of these things as being composed, we can declare them in reverse order, with the outer-most policy first:

```java
// Outer-most policy first
Failsafe.
  .with(fallback)
  .with(retries)
  .with(circuitbreaker)
  .get(() -> true)
```

The inner-most approach seems simpler at first while the outer-most approach mirrors function composition, which is sort of nice.

This isn't quite the whole story though. As part of this work, I'd like to open the door to different types of policies such as caches, timeouts and bulkheads. Some policies operate _before_ an execution takes place, such as a cache, and some operate _after_ an execution, such as a fallback.

In practice, policies will be composed internally. An execution request will be threaded through the policies, going from the outermost policy to the innermost, then the supplied callable/runnable is executed, and the result is sent back through the policies in reverse so that a failure/result can be handled if needed. 

If we introduce a cache into our set of policies:

```java
// Inner-most policy first
Failsafe.
  .with(circuitbreaker)
  .with(retries)
  .with(fallback)
  .with(cache)
  .get(() -> true)
```

or:

```java
// Outer-most policy first
Failsafe.
  .with(cache)
  .with(fallback)
  .with(retries)
  .with(circuitbreaker)
  .get(() -> true)
```

...then the inner-most approach is harder to make sense of. A cache gets used before the execution even takes place, and that becomes more clear with the outer-most approach.

Thoughts?

**Comment by jhalterman** [comment]
Shamelessly tagging a few people who dropped by previously. Please weigh in on this topic if interested :)

/cc @ben-manes @Tembrel @malpi @axelfontaine @whiskeysierra @chhsiao90

**Comment by ben-manes** [comment]
A user-defined ordering by which `with` comes first is surprising. If that was a desired goal, then I would expect a DSL to make the ordering choices more apparent (like `then`). If I glanced at code samples above, I would consider them options configuration that the library ordered based on what it considered the most logical.

**Comment by whiskeysierra** [comment]
> We could impose a logical ordering of policies supplied via `with(policy).with(policy)...` and allow a custom ordering via another API?

I'm totally in favor of allowing users to compose/order policies more freely. But I would make sure that there is only one way to do it, otherwise it's too confusing for users as well as more maintenance burden for developers.

Regarding inner-most vs outer-most. Personally I like outer-most, but both would be fine, imo. It's weird though that the execution (`get(..)`) is always the last one.

**Comment by jhalterman** [comment]
Added in 5d919d5fe5725040b4117c85fba2bc4a4dacdbc9 using outer-most-first approach. Feel free to comment if you feel this is inappropriate, but otherwise I'm closing for now.

**Comment by jhalterman** [comment]
As of e08da6ecb3e65fb831785a41e14c284eea94a726, multiple policies must be configured at the same time. This will intentional break compilation for users coming from 1.x in order to force them to think about the ordering of their policies, since ordering matters in 2.x.
