### ISSUE TITLE
withMaxDurationPerTry

### ISSUE THREAD

**Issue by ZaziroZ** [jhalterman/failsafe#16]
Hello!

Any chances of adding 'withMaxDurationPerTry' functionality? Currently, 'withMaxDuration' limits the duration of all attempts combined and not of the separate attempt.

Thanks.

**Comment by jhalterman** [comment]
Hi @ZaziroZ - Something like this could make sense, but could also yield surprising behavior where retries are aborted unexpectedly. Are you thinking, basically, that retries would stop if/when `maxDurationPerTry` is exceeded? Also, can you give me an idea what your use case (or some other use cases) for this might be?

**Comment by tryIO** [comment]
Hi! Is it something for the RetryPolicy definition? If it's so it would be better «`abortAfter(long, TimeUnit)`», but anyway, the example/case may be the large files download scenario: let's assume I have several files that I need to download, I don't know the size, I don't know my end-user's connection speed and at least I want some of them right now. If one of them is big enough to slow down the process, then skip it.

What do you think about it?
Thx!

**Comment by jhalterman** [comment]
@tryIO What you're thinking of sounds like a different use case - being able to interrupt or cancel a running execution. You can of course do that right now, manually, for synchronous executions via `Thread.interrupt` or asynchronous executions via `FailsafeFuture.cancel`, but there's not like a timer that will do it for you, if that's what you were thinking. We could consider something like that, but I'm hesitant to put it in unless there are a few really solid use cases.

**Comment by jhalterman** [comment]
Unless the OP has any more input/details on this, I'm closing for now.
