### ISSUE TITLE
Number of executions from ExecutionContext

### ISSUE THREAD

**Issue by wzomer** [jhalterman/failsafe#164]
When I get the number of executions from ExecutionContext in a failed attempt handler, it seems to ignore the initial attempt, thus giving me one less execution than I expect. Is that expected behavior or am I missing something?

**Example:**

```java
final RetryPolicy RETRY_POLICY = new RetryPolicy()
        .withMaxRetries(3);

Failsafe
        .with(RETRY_POLICY)
        .retryIf(object -> true)
        .onFailedAttempt((responseAttempt, throwable, context) -> {
            System.out.println(context.getExecutions());
        })
        .get(callable);
```

**1) Initial attempt:** 
onFailedAttempt - > context.getExecutions() returns 1

**2) First retry:**
onFailedAttempt - > context.getExecutions() returns 1 as well. Shouldn't it be 2?

**3) Second retry:**
onFailedAttempt - > context.getExecutions() returns 2. Shouldn't it be 3?

**4) Third retry:**
onFailedAttempt - > context.getExecutions() returns 3. Shouldn't it be 4?

**Comment by jhalterman** [comment]
I'm actually having trouble reproducing this against 1.1. Taking your code and making it runnable:

```java
    RetryPolicy retryPolicy = new RetryPolicy().retryWhen(true).withMaxRetries(3);
    Failsafe.with(retryPolicy).onFailedAttempt((r, f, c) -> {
      System.out.println(c.getExecutions());
    }).get(() -> true);
```

Prints:

```
1
2
3
4
```

Do you have a runnable reproducer for this?

**Comment by wzomer** [comment]
You're right, I was confused, there's no problem with Failsafe.

Sorry for this.
