### ISSUE TITLE
Fix Stream example in README

### ISSUE THREAD

**Issue by Tembrel** [jhalterman/failsafe#170]
The example of wrapping streams in the README doesn't make sense:

> We can wrap Streams:
> 
> ```java
> Failsafe.with(retryPolicy).run(() -> Stream.of("foo").map(value -> value + "bar"));
> ```
There is no terminal operation on the constructed stream, so there's nothing to fail and thus nothing to retry. I suggest either removing the example entirely or adding a terminal operation that does something. (Although then it wouldn't be wrapping a stream but rather the result of a stream operation.)

The example following this doesn't actually do anything, but it's less problematic as an example.

**Comment by jhalterman** [comment]
Agree. These were meant to hint at what's possible, but that one is just misleading. Removed in 9d2de0ad2a1884bad3f6c595f4ca7f27b91d7938.
