### ISSUE TITLE
Allow to pass collection to Failsafe.with(..)

### ISSUE THREAD

**Issue by whiskeysierra** [jhalterman/failsafe#172]
The method takes a generic array right now, which is almost impossible to work with without generating compiler warnings. I maintaining a library that builds on top of failsafe and I'd like to pass a collection of policies which I can construct on the fly beforehand.

**Comment by Tembrel** [comment]
Not an arbitrary Collection, please! Order is important, so a List, if anything.

**Comment by whiskeysierra** [comment]
Technically every collection defines an iteration order. List just defines index-based access on top. Queues, sets, etc. can all be ordered as well. But I get your point and in the end I don't care - List would be fine.

**Comment by jhalterman** [comment]
Closed by 5f4f188e48fdf16aabea49d8b3f212ea4b10e23e

**Comment by jhalterman** [comment]
This was released in 2.1.
