### ISSUE TITLE
Support dynamic circuit breaker delays

### ISSUE THREAD

**Issue by whiskeysierra** [jhalterman/failsafe#180]
Same idea as #110 but not to control delays for retries but also the circuit breaker.

The current support of a `DelayFunction` works great for retries but it only controls the retries of the particular execution that is retrying. Other, concurrent executions might still try to execute their own requests even though we technically already know that the server wants us to throttle requests. 

Since the circuit breaker (in contrast to retries) is a shared resource between executions and it also has a delay I thought it might make sense to control the circuit breaker delay in the very same way, even reusing the same interface.

**Comment by jhalterman** [comment]
Would a potential use case for this be similar to #110, such as a request that returns 429 with `Retry-After`?

**Comment by whiskeysierra** [comment]
Yes, same use case.

**Comment by jhalterman** [comment]
Released in 2.1.1
