### ISSUE TITLE
[DISCUSS] Handling Errors

### ISSUE THREAD

**Issue by gm2211** [jhalterman/failsafe#182]
The current behavior is to catch `Throwable` and wrap it in `FailsafeException` unless Runtime or handled. 

This can lead to pretty bad consequences in case of `Error` sub-classes. For example, `OutOfMemoryError` would be caught and thrown as a `FailsafeException`, and if the users of the library are not diligent and check for `instanceof Error` and rethrow, this can lead to weird system behavior.

Errors should be rethrown as is, without wrapping them in `FailsafeException`.

More details here: https://github.com/jhalterman/failsafe/pull/183#issuecomment-518862048

**Comment by gm2211** [comment]
I'm making a PR for this

**Comment by jhalterman** [comment]
Sorry, I've been away recently.

However we handle this, or not, I want the approach to be consistent throughout Failsafe. Right now, you can configure any [FailurePolicy](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/FailurePolicy.html) to handle any type of Throwable, including Fallback and RetryPolicy. So whatever we do should apply to all policies.

In theory, an `Error` is not recoverable, but in practice it's a bit more uncertain (ex: `IOError` and  `AssertionError`), so I'm happy to leave it to users to decide what to do when an `Error` is handled by their policy.

We may not want to wrap Errors at the top level with `FailsafeException`. But then again, this could lead to a somewhat inconsistent experience, where async execution results always come wrapped in a `CompletableFuture` that throws `ExecutionException` when you do a `get()`. Any thoughts on this?

Any thoughts on why not allowing Policies to handle Errors might be necessary?

**Comment by jhalterman** [comment]
I think this change will be somewhat extensive so I can take care of it, no worries.

Following the discussion your PR, I want to see what you think the correct behavior is when an `Error` is thrown. Should we call any listeners such as onFailedAttempt or onFailure?

My thoughts are we should not call any listeners, we should just complete the execution (Future) if any and return/throw the error immediately.

See also #198 to discuss how to handle Errors in event listeners.

**Comment by jhalterman** [comment]
./cc @whiskeysierra - since this is similar to #198 I'd be interested to hear your thoughts on the above.

**Comment by whiskeysierra** [comment]
> My thoughts are:
> 
> * Policies should not be able to handle `Error`s at all
> * When an Error occurs we should just complete the execution (Future) if any and return/throw the error immdiately
> * We should not call any listeners when an Error occurs

Fully agree with that.

**Comment by jhalterman** [comment]
Digging through the archives, @awallgren provided some reasonable use cases for being able to handle errors in issue #76. By default, the policies only handle Exceptions, not Errors, but if you have one of those use cases, then I can see being able to handle Errors being useful.

**Comment by jhalterman** [comment]
Pushed c6f1de187d7848b9fb11ff0922ed8c015ba6cfdb which fixes the initial issue of wrapping `Error`s. Will keep this issue open to consider further Error handling changes if needed.

**Comment by jhalterman** [comment]
@gm2211 This was released in 2.3.0.
