### ISSUE TITLE
Add details to CircuitBreakerOpenException

### ISSUE THREAD

**Issue by whiskeysierra** [jhalterman/failsafe#188]
I have a situation where I'm handling a `CircuitBreakerOpenException` in a place where I don't have access to the circuit breaker itself anymore. My primary intention is get access to the delay (the configured one is good enough for now, the remaining delay would actually be even better).

Any chance that the exception is extended with delay. Maybe even the whole circuit breaker? Transient context information like remaining delay?

**Comment by jhalterman** [comment]
Easiest thing would be to include a reference to the CircuitBreaker inside the exception. We sure could do that, which would have the added benefit of distinguishing _which_ CircuitBreaker caused an exception (if you have multiple configured).

Can you tell me more about your use case? Are you just handling an exception higher up the call stack from where the CircuitBreaker is used?

**Comment by whiskeysierra** [comment]
My use case is related to #110 and #180. I want to catch `CircuitBreakerOpenException` and translate them into `429 Too Many Requests` or `503 Service Unavailable` responses preferably with a `Retry-After` header for which I need the delay.

**Comment by jhalterman** [comment]
Released in 2.1.1

**Comment by whiskeysierra** [comment]
> My primary intention is get access to the delay (the configured one is good enough for now, **the remaining delay would actually be even better**).

Any chance we get the second part as well at some point?

**Comment by jhalterman** [comment]
Closed again via #219.
