### ISSUE TITLE
Is CircuitBreaker thread safe?

### ISSUE THREAD

**Issue by mixcloud-downloader** [jhalterman/failsafe#200]
I'm using `CircuitBreaker` like this:

    Failsafe.with(circuitBreaker).get(supplier)

I wonder now if I can share that circuitBreaker instance between multiple threads. Also it would be nice to document the thread safety aspect in `CircuitBreaker`.

**Edit:** Also, now I'm wondering if I could actually reuse that `FailsafeExecutor` from `Failsafe.with(circuitBreaker)`. So I'd like to extend my question to that as well.

**Comment by jhalterman** [comment]
`CircuitBreaker` and all policies are threadsafe to _use_ in executions. So your code example is perfectly fine to use across threads. 

That said, currently `CircuitBreaker` and `RetryPolicy` are not threadsafe to _configure_ (ex: `handle`, `.withDelay`, `withFailureThreshold`, etc). #47 considers whether RetryPolicy should be made threadsafe to configure (we should consider all policies). If you have comments or use cases on why being able to configure a `CircuitBreaker` across threads would be useful, please share.

> Also it would be nice to document the thread safety aspect in CircuitBreaker

I agree. I opened #201 for this.

> I'm wondering if I could actually reuse that FailsafeExecutor from Failsafe.with(circuitBreaker)

Absolutely. The docs [briefly mention this](https://github.com/jhalterman/failsafe#failsafe-executor), but `FailsafeExecutor` is a way of wrapping and saving a set of policies.

**Comment by whiskeysierra** [comment]
I'd like to add that circuit breaker is meant to be used for multiple
threads otherwise it's purpose is kind of questionable. Ideally you want
one for each client or endpoint that you're calling.

**Comment by Tembrel** [comment]
> `CircuitBreaker` and all policies are threadsafe to _use_ in executions. So your code example is perfectly fine to use across threads.

Maybe things have changed, but my comments in #47 (now nearly two years old!) read to me as though it is __not__ safe to share `RetryPolicy` between threads. I'll take another look.


> That said, currently `CircuitBreaker` and `RetryPolicy` are not safe to _configure_ across threads (ex: `handle`, `.withDelay`, `withFailureThreshold`, etc). #47 considers whether RetryPolicy should be made threadsafe to configure (we should consider all policies). If you have comments or use cases on why being able to configure a `CircuitBreaker` across threads would be useful, please share.

It's easier to reason about immutable instances. You don't have to worry about whether an instance will be modified (by configuration) after sharing.


> > I'm wondering if I could actually reuse that FailsafeExecutor from Failsafe.with(circuitBreaker)
> 
> Absolutely. The docs [briefly mention this](https://github.com/jhalterman/failsafe#failsafe-executor), but `FailsafeExecutor` is a way of wrapping and saving a set of policies.

I'll take a look at this to confirm. I'd like it to be true.

**Comment by jhalterman** [comment]
> It's easier to reason about immutable instances. You don't have to worry about whether an instance will be modified (by configuration) after sharing.

Agree - it's well past time to make the policies threadsafe or immutable.

**Comment by Tembrel** [comment]
The discussion seems to have moved back to #47.

**Comment by mixcloud-downloader** [comment]
Thanks guys for your quick answers. My question is answered and with #201 documenting thread safety, I can close this issue here.
