### ISSUE TITLE
How to reset failsafe?

### ISSUE THREAD

**Issue by Syed-SnapLogic** [jhalterman/failsafe#210]
Hi sir,
  Could you help me with my requirement?  My requirement is to carry out a JDBC operation with retries.  I am using the following approach:

```
RetryPolicy retryPolicy = (RetryPolicy) new RetryPolicy()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onFailedAttempt(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            LOG.warn("Error encountered while establishing connection or doing the " +
                            "read/write operation {}", event.getLastFailure().getMessage());
        })
        .onRetry(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            Throwable failure = event.getLastFailure();
            // log the retry as it seems to be a network/connection failure
            LOG.warn("Connection error encountered {}", failure.getMessage(),
                    failure);
            LOG.warn("Retrying {}th time to proceed again with a new connection",
                    event.getAttemptCount());
        })
        .handleIf(failure -> isRetryRequired((Throwable) failure));
```
isRetryRequired() checks the exception's message and decides whether to do retry ot not.  I am not showing its body here.

Next, this is how failsafe is used:
```
try {
    Failsafe
            .with(retryPolicy)
            .run(() -> {
                getJdbcConnection();
                createStatement();
                executeQueries();
            });
} catch (SQLException e1) {
    // todo
} finally {
    closeConnection();
}

void executeQueries() {
  for (String query : queryList) {
   // execute the query
  }
}
```
My question is, if any of the method fails (getJdbcConnection or createStatement or executeQuery) then I want to retry and thats how I have written the code.  However, suppose I had configured three retries and I had successfully obtained the connection in 2nd retry.  Once the connection is successful, I want to reset the Failsafe so that it can do three retries again if the connection fails next time.  How is this possible?  How can I reset the Failsafe?  Or what approach do you suggest?

**Comment by whiskeysierra** [comment]
> I want to reset the Failsafe so that it can do three retries again if the connection fails next time

What do you mean with *next time* exactly? The next time someone executes the code outlined in your second code block?

**Comment by Syed-SnapLogic** [comment]
Sorry @whiskeysierra, I updated my code.  Suppose I am running a bunch of queries against the same statement.  Lets say I have 100 queries.  After 10 queries, my connection got lost due to some network failure.  After two retries, it came back and I am continuing to execute the subsequent queries.  If I fail again, I want to go back to three retries instead of left with only one retry.  Hope that helps.

**Comment by whiskeysierra** [comment]
> After two retries, it came back and I am continuing to execute the subsequent queries.

That's not what's happening right now. If there is an exception your whole block (connect, prepare statement, execute queries) will be executed again. So all queries will be re-executed.

What you need are partial retries, if I read your requirements correctly. You'd need to implement that pattern mostly by yourself. Failsafe can give you retries for individual parts but any kind of checkpointing/resume/partial-retry would need to be done by hand.

I'd try to look into the following:
- move the connectAndPrepare part into a separate method with its own retries
- execute your queries in a loop
- put a retry around each query execution
- if a single query fails it will be retried
- you can register a retry listener to automatically reconnect upon an exception (calling the connectAndPrepare method from above)

I hope that helps.

**Comment by Syed-SnapLogic** [comment]
Let me tell you my requirement again.  I am reading 'n' number of messages from a JMS broker.  My code is as follows:
```
int totalMessagesToBeRead = 100;
int numberOfMessagesRead = 0;
RetryPolicy retryPolicy = (RetryPolicy) new RetryPolicy()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onFailedAttempt(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            LOG.warn("Error encountered while establishing connection or doing the " +
                            "read operation {}", event.getLastFailure().getMessage());
        })
        .onRetry(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            Throwable failure = event.getLastFailure();
            // log the retry as it seems to be a network/connection failure
            LOG.warn("Connection error encountered {}", failure.getMessage(),
                    failure);
            LOG.warn("Retrying {}th time to proceed again with a new connection",
                    event.getAttemptCount());
        })
        .handleIf(failure -> isRetryRequired((Throwable) failure));
try {
    Failsafe
            .with(retryPolicy)
            .run(() -> {
                getJmsConnection();  // establishes connection with the server
                createJmsSession(); // obtains session from the connection
                createJmsConsumer();  // obtains consumer instance from the session
                consumeMessages(); // reads n messages
            });
} catch (JMSException e1) {
    // todo
} finally {
    closeSession();
    closeConnection();
}

void consumeMessages() {
  while (numberOfMessagesRead < totalMessagesToBeRead) {
     Message m = getNextMessage();
     processMessage(m);
    numberofMessagesRead++;
  }
}
```
Suppose, I configured 3 retries, and after reading 10 msgs, server lost connection.  After two retries, the connection is restored, and I am continuing to read the next 90 msgs.  If again, the connection goes down after say 50 msgs, I want to do all the three retries again instead of one left.

How can I achieve that?

Can you pls reorganise my code and show me how to do it?  I want to retry whenever I fail to establish connection or obtain session or obtain consumer or read a message.

**Comment by whiskeysierra** [comment]
>  I want to retry whenever I fail to establish connection or obtain session or obtain consumer or read a message.

Is a working connection, but broken session a possibility or would you always create connection, session and consumer in one step? (It's been a while since I worked with JMS)

**Comment by Syed-SnapLogic** [comment]
Working connection but broken session is not possible in my opinion.  If a session or consumer is broken then we have to create everything (connection, session, and consumer) in the sequence again.

**Comment by whiskeysierra** [comment]
Then I'd just move the following statements to your `onRetry` listener:

```java
getJmsConnection();  // establishes connection with the server
createJmsSession(); // obtains session from the connection
createJmsConsumer();  // obtains consumer instance from the session
```

**Comment by whiskeysierra** [comment]
And if you need multiple retries for connect itself, then wrap that in another failsafe statement.

**Comment by whiskeysierra** [comment]
Something like that:

```java
int totalMessagesToBeRead = 100;
int numberOfMessagesRead = 0;
RetryPolicy<Void> retryPolicy = new RetryPolicy<>()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onRetry(event -> {
                Failsafe
                        .with(new RetryPolicy<Void>())
                        .run(() -> {
                            getJmsConnection();  // establishes connection with the server
                            createJmsSession(); // obtains session from the connection
                            createJmsConsumer();  // obtains consumer instance from the session
                        });
        })
        .handleIf(this::isRetryRequired);

try {
    Failsafe
            .with(retryPolicy)
            .run(this::consumeMessages());
} finally {
    closeSession();
    closeConnection();
}

void consumeMessages() {
  while (numberOfMessagesRead < totalMessagesToBeRead) {
     Message m = getNextMessage();
     processMessage(m);
    numberofMessagesRead++;
  }
}
```

**Comment by Syed-SnapLogic** [comment]
Thanks so much.  But still, that doesn't solve the problem in my opinion.  Suppose, number of retries is two.  Let me give my elaboration.
    - Suppose after 10 msgs, the connection went down.
    - I enter the retry block where I am instantiating connection, session and consumer.  Lets say after two retries (in the inner retry policy) the connection is back and I am continuing from 11th message.
   - Again after 10 more msgs, the connection went down.
   - Again, I will enter the retry.  Again connection is back, and I am proceeding from 21st msg.
   - Again after consuming 40 msgs, the connection went down.

There will be no more retries.  The moment I pick up a message, I want to make sure failsafe resets the retry, and it starts all over again.  Is there a way to do it?

BTW, If I simply create a instance saying new RetryPolicy<Void>(), what would be the default retry count?  1?

Again, thanks so much for your help.

**Comment by whiskeysierra** [comment]
The inner retry (reconnect) will start from 0 everytime you reconnect. It actually multiplies with the outer retries.

**Comment by Syed-SnapLogic** [comment]
Correct, if the outer retry reaches its limit then inner retry won't work.  Is there a way to reset outer retry the moment message consumption begins?

**Comment by Syed-SnapLogic** [comment]
With your code, the total number retries would be max n^2.

**Comment by whiskeysierra** [comment]
The outer retry will start every time you enter the run part. So there
shouldn't be an issue.

**Comment by Syed-SnapLogic** [comment]
@whiskeysierra , thanks so much for the help.  Is is fine to get on a call and discuss this?  May I know whats your convenient time in US PST?  Let me know.

**Comment by Syed-SnapLogic** [comment]
@whiskeysierra , the approach you suggested doesn't work.  Are you available to get on a zoom call?

**Comment by whiskeysierra** [comment]
Can you share your code and what isn't working?

**Comment by Syed-SnapLogic** [comment]
yes, I can share my code and the output as well.  It would be great if we can get on a zoom call just for few mins.

**Comment by Syed-SnapLogic** [comment]
Code:
```
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syed.failsafetest;

import java.net.ConnectException;
import java.time.Duration;
import java.util.Properties;
import javax.jms.Connection;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.naming.Context;
import javax.naming.InitialContext;
import net.jodah.failsafe.Failsafe;
import net.jodah.failsafe.RetryPolicy;
import net.jodah.failsafe.event.ExecutionEvent;

/**
 *
 * @author gaian
 */
public class Test2 {

    int totalMessagesToBeRead = 100;
    int numberOfMessagesRead = 0;
    int retryLimit = 2;
    int retryIntervalMillis = 5000;
    Session session;
    Connection connection;
    MessageConsumer consumer;

    RetryPolicy retryPolicy = new RetryPolicy<>()
            .withDelay(Duration.ofMillis(retryIntervalMillis))
            .withMaxRetries(retryLimit)
            .onRetry(event -> {
                System.out.println("outer retry num: "
                        + ((ExecutionEvent) event).getAttemptCount());
                Failsafe
                        .with(new RetryPolicy<>()
                                .withDelay(Duration.ofMillis(retryIntervalMillis))
                                .withMaxRetries(retryLimit)
                                .onRetry(event1 -> {
                                    System.out.println("inner retry num: "
                                            + ((ExecutionEvent) event1).getAttemptCount());
                                })
                                .handleIf(f -> isRetryRequired(f)))
                                .run(() -> {
                                    System.out.println("trying to get connection");
                                    getJmsConnection();  // establishes connection with the server
                                    createJmsSession(); // obtains session from the connection
                                    createJmsConsumer();  // obtains consumer instance from the session
                                    System.out.println("done reconnect");
                                    Thread.sleep(5000);
                                });
            })
            .handleIf(f -> isRetryRequired(f));

    public static void main(String s[]) {
        new Test2().run();
    }

    void getJmsConnection() throws Exception {
        Properties jndi = new Properties();
        jndi.put("java.naming.factory.initial",
                "org.apache.activemq.jndi.ActiveMQInitialContextFactory");
        jndi.put("java.naming.provider.url", "tcp://localhost:61616");
        jndi.put(Context.SECURITY_PRINCIPAL, "admin");
        jndi.put(Context.SECURITY_CREDENTIALS, "admin");
        jndi.put("connectionFactoryName", "ConnectionFactory");
        Context c = new InitialContext(jndi);
        Object cf = c.lookup("ConnectionFactory");
        if (cf != null && cf instanceof javax.jms.ConnectionFactory) {
            System.out.println("conn factory found");
        } else {
            System.out.println("undesired exit....conn factory found");
            return;
        }
        connection = ((javax.jms.ConnectionFactory) cf)
                .createConnection("admin", "admin");
        connection.start();
    }

    void createJmsSession() throws Exception {
        session = connection.createSession(true,
                Session.AUTO_ACKNOWLEDGE);
        session.run();
    }

    void createJmsConsumer() throws Exception {
        Queue Q = session.createQueue("SyedsQA");
        consumer = session.createConsumer(Q);
    }

    boolean isRetryRequired(Object o) {
        Throwable t = (Throwable) o;
        return isRetryRequired(t);
    }

    public void run() {
        try {
            getJmsConnection();
            createJmsSession();
            createJmsConsumer();
            Failsafe
                    .with(retryPolicy)
                    .run(() -> {
                        consumeMessages();
                    });
        } catch (Exception x) {
            x.printStackTrace();
        } finally {
            closeConsumer();
            closeSession();
            closeConnection();
        }
    }

    void closeSession() {
        try {
            if (session != null) {
                session.close();
            }
        } catch (Exception x) {
            // NO OP
            x.printStackTrace();
        }

    }

    void closeConnection() {
        try {
            if (connection != null) {
                connection.close();
            }
        } catch (Exception x) {
            // NO OP
            x.printStackTrace();
        }
    }

    void closeConsumer() {
        try {
            if (consumer != null) {
                consumer.close();
            }
        } catch (Exception x) {
            x.printStackTrace();
        }
    }

    void consumeMessages() throws Exception {
        System.out.println("in consuming messages ...");
        while (numberOfMessagesRead < totalMessagesToBeRead) {
            Message m = getNextMessage();
            processMessage(m);
            numberOfMessagesRead++;
            Thread.sleep(10000);
        }
    }

    Message getNextMessage() throws Exception {
        return consumer.receive();
    }

    void processMessage(Message m) throws Exception {
        System.out.println("message contents:");
        System.out.println("\t" + m.getJMSMessageID());
    }

    boolean isRetryRequired(Throwable f) {
        Throwable connectException = null;

        if (f instanceof JMSException || f instanceof ConnectException) {
            connectException = (Throwable) f;
        } else {
            Throwable cause = ((Throwable) f).getCause();
            if (cause instanceof JMSException || cause instanceof ConnectException) {
                connectException = cause;
            }
        }

        return connectException != null;
    }
}
```

Output:

--- exec-maven-plugin:1.5.0:exec (default-cli) @ FailsafeTest ---
conn factory found
in consuming messages...
message contents:
	ID:syeds-laptop-28581-1570180443240-3:1:1:1:6645
outer retry num: 1
trying to get connection
conn factory found
inner retry num: 1
trying to get connection
conn factory found
inner retry num: 2
trying to get connection
conn factory found
done reconnect
in consuming messages...
message contents:
	ID:syeds-laptop-28581-1570180443240-3:1:1:1:6645
message contents:
	ID:syeds-laptop-28581-1570180443240-3:1:1:1:6646
outer retry num: 2
trying to get connection
conn factory found
inner retry num: 1
trying to get connection
conn factory found
inner retry num: 2
trying to get connection
conn factory found
done reconnect
in consuming messages...
message contents:
	ID:syeds-laptop-28581-1570180443240-3:1:1:1:6645
message contents:
	ID:syeds-laptop-28581-1570180443240-3:1:1:1:6646

net.jodah.failsafe.FailsafeException: javax.jms.IllegalStateException: The Consumer is closed
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:383)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:210)
	at com.syed.failsafetest.Test2.run(Test2.java:111)
	at com.syed.failsafetest.Test2.main(Test2.java:64)
Caused by: javax.jms.IllegalStateException: The Consumer is closed
	at org.apache.activemq.ActiveMQMessageConsumer.checkClosed(ActiveMQMessageConsumer.java:879)
	at org.apache.activemq.ActiveMQMessageConsumer.receive(ActiveMQMessageConsumer.java:566)
	at com.syed.failsafetest.Test2.getNextMessage(Test2.java:167)
	at com.syed.failsafetest.Test2.consumeMessages(Test2.java:159)
	at com.syed.failsafetest.Test2.lambda$run$5(Test2.java:112)
	at net.jodah.failsafe.Functions.lambda$toSupplier$8(Functions.java:236)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:47)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	... 3 more

So see, the conn failed, outer retry made 1st attempt, and inner retry made two attempts, and then conn is back.

Again, later the conn failed, outer retry made 2nd attempt, and inner retry made two attempts, and conn is back.

later, again when conn went down, outer retry didn't happen as it already finished two retries.  I want to reset outer retry whenever inner retry is successful.

**Comment by whiskeysierra** [comment]
Well, you only have two retries. Either you pick a higher number, e.g.
2*totalMessagesToBeRead
or you put each individual message consumption into a retry block with two
retries. Right now it behaves correctly, since you configured at most two
retries for all messages in total. The two retries per connection attempt
seem to work nicely.

**Comment by Syed-SnapLogic** [comment]
Actually, the approach suggested in not correct.  Suppose I configured only two retries.  And the connection never came back after getting lost.  I am ending up doing 2*2 (i.e 4) retries instead of just two.

**Comment by whiskeysierra** [comment]
## Option 1

```
connect
retry (+ retry reconnect)
  loop consume      
```

- might retry connect more often because outer and inner retries multiply
- reconnect retries are independent (always do 2 retries per reconnect)

## Option 2

```
connect
retry (+ 1x reconnect)
  loop consume      
```

- might retry connect more often because retries need to account for all messages
- one message might *eat* all possible retries, leaving not enough retries for later messages

## Option 3

```
connect
loop
  retry (+ 1x reconnect)
    consume      
```

- each message is retried individually
- max retries defines how often a single message is consumed + reconnected
- retries are independent from each other
- a single message can't steal retries from later messages

**Comment by Syed-SnapLogic** [comment]
A/C to me, the following is the best approach to use Failsafe to fit my requirement:
```
int totalMessagesToBeRead = 100;
int numberOfMessagesRead = 0;
RetryPolicy retryPolicy = (RetryPolicy) new RetryPolicy()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onFailedAttempt(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            LOG.warn("Error encountered while establishing connection or doing the " +
                            "read operation {}", event.getLastFailure().getMessage());
        })
        .onRetry(e -> {
            ExecutionAttemptedEvent event = (ExecutionAttemptedEvent) e;
            Throwable failure = event.getLastFailure();
            // log the retry as it seems to be a network/connection failure
            LOG.warn("Connection error encountered {}", failure.getMessage(),
                    failure);
            LOG.warn("Retrying {}th time to proceed again with a new connection",
                    event.getAttemptCount());
        })
        .handleIf(failure -> isRetryRequired((Throwable) failure));
try {
   consumeMessages(); // reads n messages
} catch (Exception e1) {
    Throwable cause = e1 instanceof FailsafeException ? e1.getCause() : e1;
    throw cause;
} finally {
    closeSession();
    closeConnection();
}

void consumeMessages() {
 AtomicBoolean firstTime = new AtomicBoolean(true);
  while (numberOfMessagesRead < totalMessagesToBeRead) {
     Message m = getNextMessage(firstTime);
     processMessage(m);
    numberofMessagesRead++;
  }
}

Message getNextMessage(AtomicBoolean firstTime) {
    Failsafe
            .with(retryPolicy)
            .get(context -> {
                 Execution e = (Execution) context;
                 if (e.getAttemptCount() > 0) {
                       // its a retry
                      // close old resources
                      // get new resources
                 getJmsConnection();  // establishes connection with the server
                 createJmsSession(); // obtains session from the connection
                 createJmsConsumer();  // obtains consumer instance from the session
                }
                else if (firstTime.get()) {
                       firstTime.set(false);
                         // for the first time get the resources
                      getJmsConnection();  // establishes connection with the server
                      createJmsSession(); // obtains session from the connection
                      createJmsConsumer();  // obtains consumer instance from the session
                }
                return consumer.receive();
            });
}
```

**Comment by Syed-SnapLogic** [comment]
I would still recommend that Failsafe should support an option to reset the retries.

**Comment by whiskeysierra** [comment]
Why don't you put your re-connect logic in your onRetry listener? That way you wouldn't need the AtomicBoolean. Connect before your loop and within your onRetry listener. That should be enough. If you put your three function calls into a `connect` method it should be even shorter.

> I would still recommend that Failsafe should support an option to reset the retries.

In my opinion there multiple ways to deal with this situation using the current tools that are available. Resetting doesn't sound like an improvement to me.

**Comment by whiskeysierra** [comment]
```java
int totalMessagesToBeRead = 100;
int numberOfMessagesRead = 0;
RetryPolicy<Message> retryPolicy = new RetryPolicy<>()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onRetry(e -> connect())
        .handleIf(failure -> isRetryRequired(failure));
try {
   consumeMessages();
} catch (FailsafeException e) {
    throw e.getCause();
} finally {
    closeSession();
    closeConnection();
}

void consumeMessages() {
  while (numberOfMessagesRead < totalMessagesToBeRead) {
     Message m = getNextMessage();
     processMessage(m);
    numberofMessagesRead++;
  }
}

Message getNextMessage() {
    Failsafe
            .with(retryPolicy)
            .get(consumer::receive);
}
```

**Comment by Syed-SnapLogic** [comment]
If you get an exception in onRetry(), will it do retry again?

**Comment by whiskeysierra** [comment]
> If you get an exception in onRetry(), will it do retry again?

That's a good question. @jhalterman Can you answer that? I'd suggest that those cases are not retried and either ignored or fail hard with an exception. But I don't know for sure.

**Comment by Syed-SnapLogic** [comment]
I already tried and found that its not the case.  Thats why I moved everything into execution block.

**Comment by whiskeysierra** [comment]
Could be done differently:

```java
int totalMessagesToBeRead = 100;

RetryPolicy<Message> retryPolicy = new RetryPolicy<>()
        .withDelay(Duration.ofMillis(retryIntervalMillis))
        .withMaxRetries(retryLimit)
        .onRetry(e -> disconnect())
        .handleIf(failure -> isRetryRequired(failure));

try {
    consumeMessages();
} catch (FailsafeException e) {
    throw e.getCause();
} finally {
    closeSession();
    closeConnection();
}

private void consumeMessages() {
    range(0, totalMessagesToBeRead).forEach(i -> 
        processMessage(getNextMessage()));
}

private Message getNextMessage() {
    return Failsafe
            .with(retryPolicy)
            .get(() -> {
                connectIfNecessary();
                return consumer.receive();
            ]);
}

private void connectIfNecessary() {
    if (connection == null) connect();
}

private void disconnect() {
    connection = null;
}
```

**Comment by Syed-SnapLogic** [comment]
Yeah, the above approach looks good as well.  It would be great if the above example can be documented.

**Comment by jhalterman** [comment]
@whiskeysierra Do you think there's any documentable takeaway here?

**Comment by whiskeysierra** [comment]
Not sure whether this can be generalized into an example that users can take and apply more generally. Maybe as a collection of patterns using failsafe?

For the time being I'd say this issue right here will probably serve as a documentation of some kind, for those who choose to search.

**Comment by jhalterman** [comment]
👍
