### ISSUE TITLE
Using library on android

### ISSUE THREAD

**Issue by Nekromancer** [jhalterman/failsafe#212]
I can't use your library on android, since when i want to use Backoff i have to provide ChronoUnit value. Java 8 time is supported on android from version 26, and still a lot of apps are targeting much earlier versions. Is there an option to do functions overload to use TimeUnit or just miliseconds as long value?

**Comment by jhalterman** [comment]
I'm not sure about adding pre-Java 8 compatibility APIs only to have to remove them again in the future. I will say that Failsafe 1.x supported Java 6/7, and could still be used for older Android integrations:

https://github.com/jhalterman/failsafe/tree/1.x

**Comment by Nekromancer** [comment]
And APIs based on raw milliseconds? For example Resilience4j does support them. But using r4j seems like a giant overkill for a relatively simple android app

**Comment by whiskeysierra** [comment]
> But using r4j seems like a giant overkill for a relatively simple android app

Why? It has zero dependencies and its high degree of modularization allows you to pick what you really need.

**Comment by Nekromancer** [comment]
Yes, but usage is really cumbersome. When i did a pretty simple retry i had 4 questions on PR why so much code. 
Failsafe is much simple in it's apis. You have policy -> you execute policy. On r4j you have policy configuration, then you create registry, then you create Retry object and then you need to create decorated action that you can execute. Maybe i don't fully understand r4j, but that's what i get from the docs

**Comment by jhalterman** [comment]
> It has zero dependencies

It does depend on Vavr IIRC

**Comment by jhalterman** [comment]
> Failsafe is much simpler in it's apis

Thanks. FWIW, this is why I've been torn on how best to approach policy thread safety/immutability and not wanting to have separate builder APIS for policies :)

**Comment by whiskeysierra** [comment]
> On r4j you have 

- *policy configuration*: that's a `RetryPolicy` in Failsafe
- *then you create registry*: agreed, having string-named global singletons is pretty weird to have baked into the core
- *then you create Retry object*: that's closest to a `FailsafeExecutor`
- *and then you need to create decorated action that you can execute*: Failsafe only allows to execute, so it's a single step, but having the ability to decorate and execute individually could be useful

Overall, yes, it might not be as streamlined for your use case, but ideally you wouldn't put the usage allover your codebase but rather try to isolate it somewhere in a convenience function. So it shouldn't be that bad. Once you're running on the latest Android version you can start using Failsafe 2 then, by just replacing the implementation of that one function.

**Comment by Nekromancer** [comment]
Well, it's gonna be some time before we can ditch everything before android 26 since it's not that old version. But i think for now it's acceptable solution

**Comment by whiskeysierra** [comment]
> It does depend on Vavr IIRC

True. I failed to understand their gradle setup.

**Comment by Nekromancer** [comment]
Ok, resilience4j is based on java 8 time api's too, so that's useless on android. I just got a confirmation that any resilience usage on devices older than android 8 just crashes, because library cannot find `ZonedDateTime`.

So far i cannot find any Fault tolerance that actually supports android. That's pretty sad

**Comment by jhalterman** [comment]
Closing, since we don't plan to backport to pre-Java 8.
