### ISSUE TITLE
Fallback function ignored for RetryPolicy configured with handleIf

### ISSUE THREAD

**Issue by alinposho** [jhalterman/failsafe#213]
Perhaps I do not understand the documentation for the new version, but something that used to work on Failsafe 1.0.x, does not work any longer: the fallback function is ignored when the `RetryPolicy` is configured using the `handleIf` instead of the usual `handle(Exception)`. See code below:

```
public class RetryPolicyTest {


    @Test // that passes as expected
    public void given_retryPolicy_should_executeFallback() {
        // Given
        RetryPolicy<Integer> retryPolicy = new RetryPolicy<Integer>()
                .handle(Exception.class)
                .withMaxRetries(0);

        Integer fallbackValue = 100;
        Fallback<Integer> fallback = Fallback.of(fallbackValue);

        FailsafeExecutor<Integer> failsafe = Failsafe.with(retryPolicy, fallback);

        // When
        Integer result = failsafe.<Integer>get(() -> {
            throw new Exception("Expected");
        });

        // Then
        assertEquals(fallbackValue, result);
    }


    @Test // where the fallback does not get executed
    public void given_retryIfPolicy_should_executeFallback() {
        // Given
        AtomicInteger failures = new AtomicInteger(0);

        RetryPolicy<Integer> retryPolicy = new RetryPolicy<Integer>()
                .handleIf((res, ex) -> res < 0)
                .onFailure(ignored -> failures.incrementAndGet())
                .withMaxRetries(0); // somewhat contrived example to prove the point of the fallback 

        Integer fallbackValue = 100;
        Fallback<Integer> fallback = Fallback.of(fallbackValue);

        FailsafeExecutor<Integer> failsafe = Failsafe.with(retryPolicy, fallback);

        // When
        Integer result = failsafe.<Integer>get(() -> -10);

        // Then
        // This assert passes, which means that there is a failure recorded.
        assertEquals(1, failures.get());
       // This assert fails: result is -10 while the expected value is the fallback: 100
        assertEquals(fallbackValue, result);
    }
}
```

**Comment by Tembrel** [comment]
The order of the policies supplied to `Failsafe.with(...)` matters. The last policy given is actually the innermost policy to be supplied, and the first policy given is the outermost policy supplied. See [the example in the documentation](https://jodah.net/failsafe/policies/#policy-composition), where the fallback is the first, outermost policy.

You have the fallback as the innermost policy, so it is being applied __first__, passing the negative result onward. The retry policy then records a failure and returns the negative result. If you reverse the order, you should get what you expect.

The intuition is that you can view each policy as wrapping the next, so that:
```java
Integer result = Failsafe.<Integer>with(fallback, retryPolicy).get(task);
```
is interpreted like this (pseudocode:
```java
result = fallback(retryPolicy(task))
```
I'm not a fan of this part of the API, frankly. It's too easy to get wrong, and having a varargs argument for heterogeneous items seems like a bad idea. I'm not sure why @jhalterman gave up on a fluent approach, e.g., something like

```java
FailsafeExecutor<Integer> failsafe = Failsafe.firstTry(retryPolicy)
    .thenTry(fallback);
```

**Comment by jhalterman** [comment]
Yea, we want to think in terms of composition - as @Tembrel said innermost and outermost, as opposed to first and last. The reason is that policies may have behavior that is applied _before_ and/or _after_ a `task` is executed.

For example, a `RetryPolicy` is applied after a `task` is executed whereas a `CircuitBreaker` policy is applied before (and after) the `task` is executed, possibly preventing the task from being executed. This is similar with other conceivable policies such as bulkheads or rate limiters.

So a `doThis(policy1).thenThis(policy2).thenRun(task)` type of API is a bit misleading since `policy1` and `policy2` might be applied before or after the `task`... it depends on what the policy does. 

Better is to think of them as being composed: `policy1(policy2(task))`, where `policy1` might do something before `policy2`, and before the `task`, but then might do something after as well. A DSL for composition might make this a bit more clear, but I haven't had any ideas that felt great.

**Comment by alinposho** [comment]
@Tembrel 
Thanks for taking the time to respond!
Reversing the order of the policies does not make a difference in the end result, i.e. the last assert in my code sample still fails with:
```
java.lang.AssertionError: 
Expected :100
Actual   :-10
```
with the test code updated as follows:
```
    @Test
    public void given_retryIfPolicy_should_executeFallback() {
        // Given
        AtomicInteger failures = new AtomicInteger(0);

        RetryPolicy<Integer> retryPolicy = new RetryPolicy<Integer>()
                .handleIf((res, ex) -> res < 0)
                .onFailure(ignored -> failures.incrementAndGet())
                .withMaxRetries(0);

        Integer fallbackValue = 100;
        Fallback<Integer> fallback = Fallback.of(fallbackValue);

        FailsafeExecutor<Integer> failsafe = Failsafe.with(fallback, retryPolicy);

        // When
        Integer result = failsafe.<Integer>get(() -> -10);

        // Then
        assertEquals(1, failures.get());
        assertEquals(fallbackValue, result);
    }
```
So it looks like a bug to me. And even if it were to work as you mentioned, it would be inconsistent with the result in my first test(`given_retryPolicy_should_executeFallback`), which executes the fallback irrespective of the order that the retry and fallback policies are composed.

**Comment by Tembrel** [comment]
Failsafe doesn't automatically know that the -10 value that the retry policy returns as its result (when it runs out of retries) is a "bad" value. You need to have a criterion for the fallback that rejects the negative value, just as you have with the retry policy.
```java
@Test
public void given_retryIfPolicy_should_executeFallback() {
    // Given
    AtomicInteger failures = new AtomicInteger(0);

    RetryPolicy<Integer> retryPolicy = new RetryPolicy<Integer>()
	    .handleIf(this::negativeResult)
	    .onFailure(ignored -> failures.incrementAndGet())
	    .withMaxRetries(0);

    Integer fallbackValue = 100;
    Fallback<Integer> fallback = Fallback.of(fallbackValue)
	.handleIf(this::negativeResult);

    FailsafeExecutor<Integer> failsafe = Failsafe.with(fallback, retryPolicy);

    // When
    Integer result = failsafe.<Integer>get(() -> -10);

    // Then
    assertEquals(1, failures.get());
    assertEquals(fallbackValue, result);
}

private boolean negativeResult(Integer res, Throwable ex) {
    return res < 0;
}
```

**Comment by alinposho** [comment]
@Tembrel 
Sorry, this is me not reading the docs. 
Thanks for clearing this up, and sorry for wasting your time!

**Comment by jhalterman** [comment]
Do you think it's worth mentioning in the [policies docs](http://jodah.net/failsafe/policies/) that policies are independent when it comes to failure handling and that you may want to configure all policies in your chain to handle the same failures?

**Comment by Tembrel** [comment]
That, plus maybe an example showing how to do it?

**Comment by alinposho** [comment]
@jhalterman 
Thanks for taking an interest in this!
My problem was related to having the wrong mental modal of how the various parts of the library work/interact. I think the documentation already mentions that the policies are independent:

>This means the Supplier is evaluated first, then it’s result is handled by the Timeout, then the CircuitBreaker, the RetryPolicy, and the Fallback. Each policy makes its own determination as to whether the result represents a failure. This allows different policies to be used for handling different types of failures.

What might be missing (personal opinion, hence quite subjective) is a _putting it all together_ sample, where, for instance, we have Failsafe configuration with all the policies set up, and the Fallback policy is set up to catch all failures (timeout, circuit breaker open, retry condition) and return a default value. There could be a discussion here as to whether a diagram with the state transitions thorough the policies would be useful, but I'm not sure it is worth the effort, given how difficult to maintain it could prove to be.
For example:

```
public class PuttingItAllTogetherTest {

    private final static Logger log = LoggerFactory.getLogger(PuttingItAllTogetherTest.class);

    private static <E extends Throwable> boolean failedResult(Integer result, E exception) {
        // Somewhat contrived example
        return result < 0;
    }

    @Test
    public void given_FailsafeConfigurationWithTimeoutCircuitBreakerRetryPolicyAndFallback_should_executeFallback() {
        // Given
        AtomicInteger failures = new AtomicInteger(0);

        Timeout<Integer> timeout = Timeout.<Integer>of(Duration.ofSeconds(10))
                .withCancel(true)
                .onFailure(e -> log.error("Execution timeout", e.getFailure()));

        CircuitBreaker<Integer> breaker = new CircuitBreaker<Integer>()
                // Circuit breaker policy failure predicate, can be different than the other policies's
                .handleIf(PuttingItAllTogetherTest::failedResult)
                .withFailureThreshold(3, 10)
                .withSuccessThreshold(5)
                .withDelay(Duration.ofMinutes(1))
                .onOpen(() -> log.warn("Circuit breaker open."))
                .onClose(() -> log.warn("Circuit breaker closed."));


        RetryPolicy<Integer> retryPolicy = new RetryPolicy<Integer>()
                // Retry policy failure predicate, can be different than the other policies's
                .handleIf(PuttingItAllTogetherTest::failedResult)
                .onFailure(ignored -> failures.incrementAndGet())
                .withMaxRetries(1);

        Integer fallbackValue = 100;
        Fallback<Integer> fallback = Fallback
                .of(fallbackValue)
                // If we want to return a default value in those cases where the other policies's failure predicate returned true
                // We need to include it here
                .handleIf(PuttingItAllTogetherTest::failedResult)
                // Also
                .handle(// In case the circuit breaker change its state to open we fallback to a default value rather than throwing an exception
                        CircuitBreakerOpenException.class,
                        // In case there has been a timeout while waiting for the result we fallback to a default
                        TimeoutExceededException.class);


        FailsafeExecutor<Integer> failsafe = Failsafe.with(fallback, retryPolicy, breaker, timeout);

        // When
        Integer result = failsafe.get(() -> -10);

        // Then
        assertEquals(1, failures.get());
        assertEquals(fallbackValue, result);
    }
}
```

Other than that, I think you, and the other contributors, have done a great job putting together a succinct, but comprehensive, documentation for a great library.

**Comment by jhalterman** [comment]
> There could be a discussion here as to whether a diagram with the state transitions through the policies would be useful

Thanks for suggesting this. I agree a timing diagram that shows how execution flows through the policies in some example would be helpful. Failsafe's policy composition takes inspiration from Polly, which includes something like this in its docs: https://github.com/App-vNext/Polly/wiki/PolicyWrap#operation

I'll add something similar for Failsafe.

**Comment by Tembrel** [comment]
The nice thing about that diagram is that it reinforces the left-to-right, outer-to-inner orderig of `Failsafe.with(policies)`.
