### ISSUE TITLE
Not throw exception.

### ISSUE THREAD

**Issue by RuslanSafa** [jhalterman/failsafe#217]
There is a task in case of the end of attempts not to throw the exception.
`Failsafe.with(
            new RetryPolicy<Void>()
                .handle(Exception.class)
                .withMaxAttempts(2) // unlimited
                .withMaxDuration(retryTimeout))
        .run(this::test);`
How can I achieve this?

**Comment by whiskeysierra** [comment]
You need to register a fallback.

**Comment by jhalterman** [comment]
Ex, something like:

```java
    RetryPolicy<Object> retryPolicy = new RetryPolicy<>()
      .withMaxAttempts(2)
      .withMaxDuration(Duration.ofSeconds(2));
    Fallback<Object> fallback = Fallback.of("");
    Failsafe.with(fallback, retryPolicy).run(this::test);
```

**Comment by Tembrel** [comment]
@RuslanSafa - Note that `.handle(Exception.class)` is a no-op since this is the default handling behavior. Also see #202 and #213 for commonly encountered problems having to do with fallbacks and policy ordering.

**Comment by RuslanSafa** [comment]
Th's, I will try

**Comment by jhalterman** [comment]
```As the sentence can provide a constant - Fallback.EMPTY```

Yea, I realized when I left that comment something like that was needed, and I added `Fallback.VOID` in master.

**Comment by RuslanSafa** [comment]
@jhalterman Excellent. th's
