### ISSUE TITLE
reconnect() before retry

### ISSUE THREAD

**Issue by nemecec** [jhalterman/failsafe#227]
I have the following use-case which Failsafe does not seem to cover. Or maybe it covers and I just don't know how to use the library properly.

I want to perform an operation over some network protocol. In case the operation fails, I want to force a reconnect (disconnect+connect) and try again.

Retrying the operation with Failsafe is trivial. However, I do not understand, how can I add the reconnect logic to it. I tried to add it as onRetry() listener but that has the undesired side-effect that any errors thrown from reconnect() logic will be swallowed. I would like those errors to be handled with the same logic as the main operation. The reconnect and main operation would be kind of combined into a single "composite retry" operation. But the reconnect would only be run in case it is a retry (skipped on first attempt).

Some example scenarios with 2 retries would result in following activities.

Try fails, reconnect fails, reconnect fails:
1. try the main operation
2. in case main operation fails, perform reconnect
3. in case reconnect fails, try reconnect again
4. in case reconnect still fails, exit with error

Try fails, reconnect fails, reconnect succeeds, retry fails:
1. try the main operation
2. in case main operation fails, perform reconnect
3. in case reconnect fails, try reconnect again
4. in case reconnect succeeds, retry main operation
5. in case main operation fails, exit with error

Try fails, reconnect fails, reconnect succeeds, retry succeeds:
1. try the main operation
2. in case main operation fails, perform reconnect
3. in case reconnect fails, try reconnect again
4. in case reconnect succeeds, retry main operation
5. in case main operation succeeds, exit with no error

Try fails, reconnect succeeds, retry fails, reconnect fails:
1. try the main operation
2. in case main operation fails, perform reconnect
3. in case reconnect succeeds, retry main operation
4. in case main operation fails, try reconnect again
5. in case reconnect fails, exit with error

Try fails, reconnect succeeds, retry succeeds:
1. try the main operation
2. in case main operation fails, perform reconnect
3. in case reconnect succeeds, retry main operation
4. in case main operation succeeds, exit with no error

**Comment by whiskeysierra** [comment]
I'd suggest to read the discussion in #210. Maybe that already answers your question.

**Comment by nemecec** [comment]
Thank you for your comment, @whiskeysierra!

That issue seems to be about a different use-case (and quite weird one, if you ask me). However, I did learn from there that current way of solving it would be something like this:
```java
  Failsafe.with(retryPolicy)
      .get(context -> {
        Execution context = (Execution) context;
        if (context.getAttemptCount() > 0) {
          // it's a retry
          reconnect();
        }
        mainOperation();
      });
```

**Comment by jhalterman** [comment]
You could also do something like:

```java
RetryPolicy<Object> rp = new RetryPolicy<>().onRetry(e -> reconnect());
Failsafe.with(rp).get(this::mainOperation);
```

Conceptually a RetryPolicy is separate from the execution, allowing a RetryPolicy to be reused for different executions. In this example the two are somewhat coupled since RetryPolicy is doing a `reconnect`. But this approach is fine if the RetryPolicy is not reused.

**Comment by nemecec** [comment]
Thank you for the comment, @jhalterman!

In your example, what happens in case reconnect() fails and throws an exception?
My understanding is that `onRetry` is a listener and when exception is thrown from a listener, it is silently swallowed. At least it is not handled in the same manner as exception thrown from the "main logic". Correct?

In that case, this is not a solution for my scenario.

**Comment by Tembrel** [comment]
Note that if #229 is implemented, you'll be able to rewrite your code above as:
```java
... = Failsafe.with(retryPolicy)
  .get(ctx -> {
    if (ctx.isRetry())
        reconnect();
    mainOperation();
  });
```
which reads pretty clearly.

**Comment by jhalterman** [comment]
> what happens in case reconnect() fails and throws an exception?

Exceptions in event listeners, such as `onRetry` are ignored - they don't effect the main execution at all. If you want `reconnect()` exceptions to be handled by Failsafe, the approach you mentioned is ideal.

**Comment by nemecec** [comment]
Ok, thank you for the confirmation.

**Comment by jhalterman** [comment]
@nemecec As an aside, are you using Failsafe at ZeroTurnaround? If so, can I add them to the [users list](https://jodah.net/failsafe/whos-using/)?

**Comment by nemecec** [comment]
@jhalterman, I'm not at ZeroTurnaround anymore. Judging by their current (remaining) products, I doubt if they use it. Cool project, nevertheless. :-)

**Comment by jhalterman** [comment]
I wanted to follow up for posterity with one other idea that came up in #246 about performing reconnects, for example, using a Fallback. Ex:

```java
private CompletionStage<String> fetchDataWithRetry() {
  Fallback<Object> fallback = Fallback.ofAsync(e -> {
    reconnect(e.getLastFailure());
  }).handle(IllegalStateException.class);
  RetryPolicy<Object> retryPolicy = new RetryPolicy<>().withMaxRetries(2);
  return Failsafe.with(retryPolicy, fallback)
    .getStageAsync(e -> fetchData(e.getAttemptCount()));
}

void reconnect(Throwable failure) {
  // ... reconnect
  throw (Exception) failure;
}
```

It's not perfect at the moment, but it's another option to be aware of.
