### ISSUE TITLE
How can I implement an X-Retry-After?

### ISSUE THREAD

**Issue by mikebell90** [jhalterman/failsafe#228]
Let's say an http service is responding with a 429, and and an X-Retry-After in response to a Failsafe client call. I can see I can dynamically vary RetryPolicy with the DelayFunction, but not sure how I could conveniently pass a context like the Header value?

**Comment by Tembrel** [comment]
Right now I think the best you can do is bake the delay into the next attempt with `Thread.sleep`, using [execution context](https://jodah.net/failsafe/javadoc/net/jodah/failsafe/FailsafeExecutor.html#getAsync-net.jodah.failsafe.function.ContextualSupplier-) to retrieve the `X-Retry-After` value.

You'd have to pick your scheduler carefully and think about what happens when a lot of requests get 429 and X-Retry-After at once: Does it use up lots of threads without limitation?

**Comment by jhalterman** [comment]
To be clear, you want to pass a header value from one response into the next request? Or you just want to delay your retries based on a response header? Re: the second, you can do something like (untested):

```
new RetryPolicy<HttpResponse>
  .computeDelay(ctx -> {
    Duration.ofSeconds(ctx.getLastResult().getHeader("x-retry-after"));
  });
```

...but it seems like you already saw that.

**Comment by Tembrel** [comment]
I'm not clear on what `computeDelay` does as a member of `RetryPolicy`.

But I see that `DelayFunction` does take a last result, last failure, and execution context, so I was entirely wrong above. (I'll edit it to say so.)

How does this look?
```java
RetryPolicy<HttpResponse> retryPolicy = new RetryPolicy<HttpResponse>()
    .handleResultIf(this::gotRetryAfter)
    .withDelay((result, failure, ctx) -> delayFromRetryAfterHeader(result));
```
where `gotRetryAfter` and `delayFromRetryAfterHeader` are both instance methods that take an `HttpResponse`.

**Comment by jhalterman** [comment]
Apologies, `computeDelay` may as well have been package private since `withDelay(DelayFunction)` was the intended API. I edited my post above.

**Comment by whiskeysierra** [comment]
That's exactly how I'm using this feature in Riptide: https://github.com/zalando/riptide/blob/master/riptide-failsafe/src/main/java/org/zalando/riptide/failsafe/RetryAfterDelayFunction.java

**Comment by mikebell90** [comment]
Yep, makes sense, thanks. The key was I embarassingly didn't notice handleResultIf, so was scratching my head "Geez if all I have is the exception and the execution context" ;)

Thanks all.
