### ISSUE TITLE
Re-work internal threading

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#230]
While thinking about #207, I got to wondering if internal threading should work the way it does. Currently, an async execution causes a thread to be created immediately before the policies and the user-provided `supplier` are executed. Really though, it's only the user-provided `supplier` that needs to cause the creation of a thread. The initial call through the policies can happen on the calling thread.

I'm not sure what the pros/cons are of doing this either way, but I'll push a commit just to try it out in case anyone has thoughts.

**Comment by Tembrel** [comment]
I took a quick skim. I'll try to reason it through more carefully, but I like this a lot.

**Comment by jhalterman** [comment]
Some notes on the commit:

- It changes from creating a thread immediately when evaluating policies to just [wrapping the user's supplier](https://github.com/jhalterman/failsafe/commit/b221a21b2f8e31020d4a7a04a338acb877b88233#diff-1c0ebf1fe211327fe04171a91aeebb8cR50) with a thread on the first call, but [not on any subsequent calls](https://github.com/jhalterman/failsafe/commit/b221a21b2f8e31020d4a7a04a338acb877b88233#diff-54d25783e93300ff83389b67fe80624aR99) since any possible retries will already be [performed on a separate thread](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicyExecutor.java#L121).

**Comment by jhalterman** [comment]
I'm thinking of merging this change unless there are any objections...

**Comment by jhalterman** [comment]
Closed by d69a15ac62d9f64063b1256bbf879905bae8b08b.

**Comment by jhalterman** [comment]
Released in 2.3.4.

**Comment by timothybasanov** [comment]
Thank you! Could you add one more step? Make a retry executor to schedule execution with a delay of 0 for a retry. Or more generally, never to execute application logic (non-Failsafe) on a scheduled thread pool. This way DelayedExecutor would no longer be necessary as only small CPU bound tasks would on a scheduled pool.

**Comment by jhalterman** [comment]
> This way DelayedExecutor would no longer be necessary as only small CPU bound tasks would on a scheduled pool.

Do you have a pointer or more details about what you mean? Are you thinking of something you saw in the code?

Failsafe's RetryPolicyExecutor [passes whatever delay is requested to whatever scheduler is configured](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicyExecutor.java#L121). By default, no no scheduler is configured, Failsafe uses the [`DelegatingScheduler`](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/util/DelegatingScheduler.java) which will executes tasks [immediately](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/util/DelegatingScheduler.java#L153-L156), using a ForkJoinPool (usually the common pool), if there is no delay, and only add a separate scheduled delay if needed.
