### ISSUE TITLE
Retry and Abort policy exceptions in one hierarchy

### ISSUE THREAD

**Issue by jamazurak** [jhalterman/failsafe#238]
When I used retry policy which should retry on _IOException_ and _SocketTimeoutException_, but abort on _InterruptedIOException_, then execution was aborted on _SocketTimeoutException_.
The exception hierarchy is _IOException_ - _InterruptedIOException_ - _SocketTimeoutException_.
I'm right that the execution was aborted because _SocketTimeoutException_ is a descendant of _InterruptedIOException_, and abort handling has a **higher** priority than the retry handling?
And if I include the _IOException_ for retry then I don't need to add the _SocketTimeoutException_ to the retry list?

**Comment by jhalterman** [comment]
> I'm right that the execution was aborted because SocketTimeoutException is a descendant of InterruptedIOException, and abort handling has a higher priority than the retry handling?

Right - Since `SocketTimeoutException` _is_ an `instanceof` `InterruptedIOException`, then the abort is triggered.

> if I include the IOException for retry then I don't need to add the SocketTimeoutException to the retry list?

Right. 

In your case instead of doing an instanceof check, you might want to check if the exact exception name matches? In that case you could do something like (untested):

```java
retryPolicy
  .retryOn(IOException.class)
  .abortIf(failure -> failure.getClass().getName().equals("my.package.SocketTimeoutException"));
```

**Comment by whiskeysierra** [comment]
You can check on the class instance directly: e.getClass() ==
SocketTimeoutException.class

**Comment by jamazurak** [comment]
Thank you all.
