### ISSUE TITLE
Put "retrying" in README for SEO :-)

### ISSUE THREAD

**Issue by szpak** [jhalterman/failsafe#239]
Some time ago I was looking for some Java library for retrying an operation waiting for the server response to contain information about finished processing of previously accepted request (so not strict "failure handling"). Unfortunately, I didn't find Failsafe as it was too low in search results for "retrying java library". Luckily a colleague of mine suggested Failsafe and I like it.

In hindsight I could search for "retry java library" with a better chance to find Failsafe (although that keyboard doesn't exist in README and/or project description on GH), but I think it would be good to cover also people looking for "retrying" in Java.

> Failsafe is a lightweight, zero-dependency library for handling failures (and retrying in general) in Java 8+

?

As the original description is very consist it might be added later on in the README to do not "derate" it.

**Comment by jhalterman** [comment]
Fixed in 8b6ec6cd63039230e27de2314ded453259722fe5.
