### ISSUE TITLE
Failsafe vs Hystrix

### ISSUE THREAD

**Issue by charphi** [jhalterman/failsafe#24]
I'd like to have a small comparison (pros/cons) between your library and others such as Hystrix.
It might help people decide which library best suits their needs.

**Comment by jhalterman** [comment]
Let me quickly caveat this by saying I am not an expert or even a user of Hystrix, so what I can comment is based on my reading of its docs. 

Failsafe is intended to be lightweight and to blend as seamlessly into your code as possible while Hystrix is a bit more imposing but offers many more features as a result, such as response caching, request collapsing and automatic threadpool management. Generally, Hystrix is more oriented around the execution of remote requests, and offers features around that, while Failsafe is more general purpose failure handling for any type of execution. To summarize a few of these differences:

* Executable logic can be passed through Failsafe as simple lambda expressions or method references. In Hystrix, your executable logic needs to be placed in a HystrixCommand implementation.
* Failsafe executions are run either synchronously or asynchronously on a user supplied ThreadPool / Scheduler. Hystrix executes commands on internal thread pools, with one pool per dependency.
* Failsafe circuit breakers are somewhat more configurable than Hystrix circuit breakers. For example, Failsafe circuit breakers support execution timeouts and configurable success thresholds (Hystrix only performs a single execution when in half-open state to determine whether to close a circuit).
* The Hystrix API makes heavy use of RxJava Observables, where command executions can be converted to Observables. Failsafe executions are either synchronous, or return [FailsafeFuture](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/FailsafeFuture.html).

Those are the main thoughts that stand out to me.

Reference: https://github.com/Netflix/Hystrix/wiki/How-it-Works#CircuitBreaker

**Comment by charphi** [comment]
Thanks for you quick answer!

**Comment by axelfontaine** [comment]
This should be copy-pasted in the main README.md (which BTW is a little confusing right now as the listeners API has changed from what is available on Maven Central...)

**Comment by jhalterman** [comment]
@axelfontaine Will do. Also, rolled back changes to the README for the listeners API until the next release has gone out.

**Comment by jhalterman** [comment]
This content has been moved to a wiki page so it can be better maintained as needed:

https://github.com/jhalterman/failsafe/wiki/Comparisons#failsafe-vs-hystrix

**Comment by gabrielgiussi** [comment]
@jhalterman I don't quite understand the following point:

> Failsafe circuit breakers can be shared across different executions against the same component (such as a web service), so that if a failure occurs, all executions against that component will be halted by the circuit breaker.

This isn't like THE way that circuit breakers should work? If each execution will have his own circuit breaker it will never fail fast (aka open CB) and won't accomplish any purpose.
What is the scenario that you are specifying with this point?

Thanks.

**Comment by jhalterman** [comment]
@gabrielgiussi Yes, but depending on the CircuitBreaker implementation, applying the same breaker to a set of related executions can carry some constraints. In Hystrix (which I am not an expert on), you might place a group of operations in the same HystrixCommand. But doing so means that all of the executions in that command will be subject to the same configuration/fallback options.
