### ISSUE TITLE
Fallback success and failure policy listeners

### ISSUE THREAD

**Issue by sanoopps** [jhalterman/failsafe#248]
Hi,

I've a question on using policy listeners with `Fallback` policy. I understand that `onSuccess()` is executed when the fallback is executed successfully. 

However I'm observing something I didn't quite expect. For e.g., with the below `Fallback` policy configured to execute on `null` result, I would not expect `Got from fallback` to be printed because the main call returns non-null and so fallback logic itself should not be executed.

```java
        Fallback<String> fallback = Fallback.of("hello")
                .handleResult(null)
                .onSuccess(e -> System.out.println("Got from fallback"))
                .onFailure(e -> System.out.println("Failed to get from fallback"));

        String result = Failsafe.with(fallback)
                .get(() -> "world");

        System.out.println("Result is " + result);
```

But I get the below output -
```
Got from fallback
Result is world
```

Why did the `onSuccess()` listener get executed?

And if I change the main call to return `null`, then the `onFailure()` listener is getting executed even though the fallback executes successfully and returns the fallback value.
```java
        Fallback<String> fallback = Fallback.of("hello")
                .handleResult(null)
                .onSuccess(e -> System.out.println("Got from fallback"))
                .onFailure(e -> System.out.println("Failed to get from fallback"));

        String result = Failsafe.with(fallback)
                .get(() -> null);

        System.out.println("Result is " + result);
```

Output - 
```
Failed to get from fallback
Result is hello
```

Perhaps my understanding is incorrect or I'm being daft. 😅

**Comment by Tembrel** [comment]
The success here refers to whether the primary action &mdash; the result of `FailsafeExecutor.get` &mdash; was successful. If the policy does not need to handle the result of the action, it's a success; if the policy __does__ have to handle it and the fallback value has to be used, it's seen as a failure.

Fallback is a bit of an odd duck, in this respect. It makes more sense in the context of a sequence of policies, where the "best" case is that none of the policies need to handle anything: That's a success, and anything else necessarily involves a some failure along the way.

**Comment by sanoopps** [comment]
Thanks! That was my guess too. The documentation example (quoted below) did not help.

> Fallbacks support the standard policy listeners which can notify you when a fallback fails:
> 
> fallback.onFailure(e -> log.error("Failed to connect to backup", e.getFailure()));
> Or succeeds:
> 
> fallback.onSuccess(e -> log.info("Connected to backup"));

From that, it looks like `onSuccess()` is executed on fallback succeeding (i.e. `FailsafeExecutor.get` failing and the fallback succeeding) and `onFailure()` is executed on fallback failing (i.e. `FailsafeExecutor.get` failing and the fallback failing as well).

I think the documentation needs to be clearer in that case.

**Comment by Tembrel** [comment]
Agreed, that example could be cleaned up.

**Comment by jhalterman** [comment]
> If the policy does not need to handle the result of the action, it's a success; if the policy does have to handle it and the fallback value has to be used, it's seen as a failure.

It's not exactly like that actually (explained below), which means we need to improve the docs or reconsider how this works if it doesn't make sense.

> Why did the onSuccess() listener get executed?

This could be clarified indeed. The policy level `onSuccess` and `onFailure` methods are based on whether the policy was successful in handling a a supplied execution. Each policy makes its own determination about what is a success/failure. By default, policies treat exceptions as failures, else they use any "handle" method you configure to determine what is a failure.

If a policy decides that a failure has occurred (according to its configuration), then it tries to handle it. For a retry policy this means retrying the execution. For fallback this means producing an alternative ("fallback") result. But then we have to decide if the new result itself is a success or failure, which again uses the policy's configuration.

In the example you posted about, the fallback treats `null` as a failure. So if/when the fallback is triggered, any non-`null` result is considered a success. If the fallback returns another `null` then the fallback is considered to have failed (according to the `handleResult(null)` configuration). 

Being able to signal the result of the policy's handling of an execution in this way is important. Hopefully this clarifies the example in the docs as well, let me know if not, and if you have thoughts on where to improve the docs around this stuff.

**Comment by Tembrel** [comment]
OK, but the observed behavior in the examples above seems to contradict that new wording.

Both examples have `.handleResult(null)` so, in the first example, executing `() -> "world"` is a success: The supplied result is not null and the fallback policy does not handle it. And indeed `onSuccess` is called.

Executing `() -> null` supplies a null result, and because of its failure configuration the fallback policy handles it and produces `"hello"`. By that new wording, you would expect `onSuccess` to be called, because the supplied result is a failure but the policy __was__ able to produce a successful result. Yet the observed behavior was that `onFailure` is called.

**Comment by jhalterman** [comment]
Thanks @Tembrel, I misread this. This is a bug according to how these event listeners are intended to work. I would be interested to know if you think there's a problem with them working this way, basically, that `onSuccess`/`onFailure` represents the result of the policy's attempted handling of an execution, not just the initial execution. In the case of a RetryPolicy, for example, this represents all retries having been exhausted and still failing.

**Comment by Tembrel** [comment]
I don't think it's a problem for them to work the way they do now. It's intuitive (to me, at least). A fallback value having to be used seems "less good" than if it does __not__ have to be used, so the former feels like a relative failure and the latter a relative success. A retry policy eventually getting an acceptable result feels like a success and exhausting all retries with no acceptable result feels like failure.

**Comment by jhalterman** [comment]
> A fallback value having to be used seems "less good" than if it does not have to be used, so the former feels like a relative failure and the latter a relative success

Yea, using the fallback indicates something failed, but in a similar way to using a retry policy indicates something failed. As you say, if the retry policy has to be used but eventually gets an acceptable result that's a success. My goal was symmetry with fallbacks, where if a fallback has to be used but gets an acceptable result, that's a success. Do you think that make sense?

**Comment by Tembrel** [comment]
I see what you mean by consistency, but it comes at the cost of evaluating the handling condition on the fallback value or computation, which seems like a needless test.

While a retry policy is a potential loop, where the result of an attempt gets fed to the handling condition to see if we have to retry, a fallback is a fork in the road: Use the incoming result unless it meets the handling condition, in which case use an alternative result or computation. I wouldn't have expected the alternative result to then be fed back to the handling condition for the sole purpose of deciding whether to call `onSuccess` or `onFailure`.

A lot of the time people will use fallbacks to provide an acceptable result when given an unacceptable one, in which case applying the interpretation of the wording you committed above would mean never getting `onFailure`.

But I could live with either interpretation.

**Comment by jhalterman** [comment]
> I wouldn't have expected the alternative result to then be fed back to the handling condition for the sole purpose of deciding whether to call onSuccess or onFailure.

Yea, I could see that being a fair assumption. It might depend on how you're using the fallback though. If it's a constant value, then yea, it's one extra needless evaluation. The use case I had in mind is [similar to the docs](https://jodah.net/failsafe/fallback/#event-listeners), where a Fallback is used to compute some alternative result such as connecting to a backup service. Since that computation also might fail, we want a way of knowing that.

> A lot of the time people will use fallbacks to provide an acceptable result when given an unacceptable one, in which case applying the interpretation of the wording you committed above would mean never getting onFailure.

Assuming we were able to produce an acceptable result (ex: the backup connection is successfully established), then yea, `onFailure` is never called. But there are use cases where it could be called.

Overall, it sounds like we have two different potential events that could be expressed through `onFailure`: that the policy was triggered because of some initial failure, and that the eventual result of the policy was a failure. Maybe two separate event listeners are in order.

**Comment by Tembrel** [comment]
`onHandled` ?

**Comment by jhalterman** [comment]
It occurred to me an `onHandled` type of event is basically the same as `RetryPolicy.onFailedAttempt`. Perhaps that one can be moved up somewhere more common.

**Comment by sanoopps** [comment]
Thank you @jhalterman and @Tembrel for the responses.

>The use case I had in mind is similar to the docs, where a Fallback is used to compute some alternative result such as connecting to a backup service. 

I'm using `Fallback` policy for something like that - I'm in the midst of migrating users from one database to another and using `Fallback` policy to fall back to the legacy database if a user is not found in the new one. It is not a failure per se if I get the user from legacy - I just want to know when and how many times the service got the user from legacy database and I'm using `onSuccess()` policy listener for that.

I've used success and failure policy listeners with `RetryPolicy` as well and was expecting these policy listeners to work consistently across all policy types.

**Comment by jhalterman** [comment]
> I've used success and failure policy listeners with RetryPolicy as well and was expecting these policy listeners to work consistently across all policy types.

Just to confirm, that means you'd expect Fallback to work as I described it, where `onSuccess`/`onFailure` are based on whether the fallback result (backup connection)?

**Comment by sanoopps** [comment]
Yes, I'd expect them to work based on fallback's handling status i.e. `onSuccess()` on (main execution failing and) fallback succeeding and `onFailure()` on (main execution failing and) fallback failing.

**Comment by Tembrel** [comment]
What about when main execution succeeds and fallback isn't used? Neither
onSuccess not onFailure?

**Comment by jhalterman** [comment]
> What about when main execution succeeds and fallback isn't used? Neither
onSuccess not onFailure?

That's something I've been wondering as well. Current behavior is to call onSuccess at the policy level, even though the policy doesn't technically handle anything.
