### ISSUE TITLE
Simplify Listeners API

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#26]
Currently the listeners API requires a separate object instantiation for all cases:

```
Failsafe.with(retryPolicy)
  .with(new Listeners()
    .onFailure(e -> log.error(e))
    .onSuccess(cxn -> log.info("created connection: {}", cxn);
  .get(this::connect);
```

The idea behind this was that a set of Listeners could be reused and shared, but I'm not sure there's much of a use case for that since Listeners tend to be execution specific. That said, I think it makes sense to streamline this by allowing listener registration directly at the top level API:

```
Failsafe.with(retryPolicy)
  .onFailure(e -> log.error(e))
  .onSuccess(cxn -> log.info("created connection: {}", cxn);
  .run(this::connect);
```

In this setup, individual listeners could still be reused. This change will also remove the listener methods from `FailsafeFuture` since they can be registered instead via the `Failsafe` API.

A  `Listeners` class will still be retained for Java 6 / 7 compatibility via the `with(Listeners)` method, but will not be used for listener registration, only overrides:

```
Failsafe.with(retryPolicy)
  .with(new Listeners<Connection>() {
    public void onFailure(Throwable failure) {
      log.error(e);
    }
  })
  .get(this::connect);
```

**Comment by jhalterman** [comment]
@axelfontaine Since you stumbled on this change, do you have any comments? It would be much appreciated.

**Comment by axelfontaine** [comment]
The new top-level API is actually how I intuitively tried to do it before I looked at the docs and tried completion in my IDE and got confused :-)

**Comment by jhalterman** [comment]
Glad to hear :) Hope to get it released soon :)

**Comment by axelfontaine** [comment]
Excellent work BTW. Simple, very focussed and high quality library! :+1:
