### ISSUE TITLE
Timeout policy data race between injectTimeout and cancelDelegates

### ISSUE THREAD

**Issue by timothybasanov** [jhalterman/failsafe#262]
Seemingly there is a data race between these two calls in `TimeoutExecutor`:
* `future.cancelDelegates(canInterrupt, false);`
* `timeoutFuture.set(...); future.injectTimeout(timeoutFuture.get());`

It's possible that `cancelDelegates` is called first and cleans up a list of delegates. Then `injectTimeout` adds a new element to a list. I'm not sure if this would actually cause some issues, I was just surprised to not to see `Thread.yield()` anywhere.

> This is not a contribution

**Comment by Tembrel** [comment]
Was this already fixed? Maybe I'm missing something, but `cancelDelegates` is synchronized, and `future.injectTimeout` is called within `synchronized (future)  {...}`. So if the call to `cancelDelegates` is somehow reached very quickly, it will still block until the body of the `synchronized (future)` completes.

**Comment by timothybasanov** [comment]
Yes! It's all good, I misread the code.
