### ISSUE TITLE
timing out without cooperation

### ISSUE THREAD

**Issue by adrian-herscu** [jhalterman/failsafe#271]
With FailSafe, shouldTimeout works only if callable sleeps but not in long loop.
With Guava's SimpleTimeLimiter, shouldTimeout2, it works with the long loop too.
Anything I am missing?

```
    @Ignore
    @SneakyThrows
    @Test(expectedExceptions = ExecutionException.class,
        timeOut = 1_100, // millis
        invocationCount = 10)
    public void shouldTimeout() {
        val timeout = Duration.ofSeconds(1);
        assertThat(Failsafe
            .with(Timeout
                .of(timeout)
                .withCancel(true)
                .onFailure(e -> log.debug("timed out {}", e)))
            .with(SCHEDULER)
            .getAsync(() -> {
                log.debug("executing");
                // ISSUE https://github.com/jhalterman/failsafe/issues/271
                // it works with sleep though
                // sleep(timeout.plusSeconds(1).toMillis());
                val startMillis = currentTimeMillis();
                do {
                    // just loop for 2 seconds
                } while (currentTimeMillis() - startMillis < 2_000);
                log.debug("returning exceeding timeout; interrupted {}",
                    currentThread().isInterrupted());
                return true;
            })
            .get(),
            is(true));
    }

    @SneakyThrows
    @Test(expectedExceptions = TimeoutException.class,
        timeOut = 1_100, // millis
        invocationCount = 10)
    public void shouldTimeout2() {
        val timeout = Duration.ofSeconds(1);
        assertThat(SimpleTimeLimiter.create(SCHEDULER)
            .callWithTimeout(() -> {
                log.debug("executing");
                val startMillis = currentTimeMillis();
                do {
                    // just loop for 2 seconds
                } while (currentTimeMillis() - startMillis < 2_000);
                log.debug("returning exceeding timeout; interrupted {}",
                    currentThread().isInterrupted());
                return true;
            }, timeout.getSeconds(), TimeUnit.SECONDS),
            is(true));
    }
```

**Comment by Tembrel** [comment]
If you strip away the testing framework stuff and just run these as standalone programs, both methods throw the expected exception, TimeoutExceededException (wrapped in ExecutionException) for the Failsafe Timeout case, and TimeoutException for the Guava TimeLimiter case. The difference is that in the Failsafe case, the task runs to completion in spite of the `withCancel(true)` call, and in the Guava case it does not, or rather appears not to.

As I wrote in [this comment](https://github.com/jhalterman/failsafe/issues/263#issuecomment-684133943):
> In general, Failsafe users should not expect timeouts to stop the execution of tasks. If you really want to ensure that tasks stop when they time out, you must carefully craft them to be cancellable.

In this case, for example, passing in the Failsafe execution context and checking that context periodically for cancellation would make the task more cancellation-responsive:
<pre><code>
    .getAsync(<b>ctx</b> -> {
	log.debug("executing");
	val startMillis = currentTimeMillis();
	do {
	    // just loop for 2 seconds
	} while (<b>!ctx.isCancelled()</b> && currentTimeMillis() - startMillis < 2_000);
	log.debug("returning; cancelled {}", <b>ctx.isCancelled()</b>);
	return true;
    })
</code></pre>

It's notoriously difficult to simulate real work with spin loops, and it's hard to draw conclusions about what a spin loop is really doing. In the absence of blocking or synchronizing actions, the runtime environment can perform all sorts of optimizations that are hard to predict. I generated some truly bizarre results using the original version of `shouldTimeout`, replacing the logging statements with atomic increments of two `AtomicLong` variables: Even though both variables were incremented once in the for-loop, they would end up with different values!

**Comment by adrian-herscu** [comment]
Thanks for the prompt reply :)
1. I do not have control over the code run by the working thread -- it is some framework code -- hence I cannot put `isCancelled` or `isInterrupted` logic inside
2. 1. I don't care about working thread continuing to work after timeout
3. I do care that the controlling thread gains control after timeout -- that does not happen with Failsafe but happens with Guava

**Comment by Tembrel** [comment]
Internally, Guava's TimeLimiter is just doing a timed `Future.get` and, if this times out, `Future.cancel(true)`. In this particular (contrived) case, you can do the same thing with the CompletableFuture returned by `FailsafeExecutor.getAsync`.

More generally, however, you want to be able to have things like retries and circuit breakers without holding up Failsafe's execution with long-running tasks. Failsafe's Timeout policy can only be effective in such cases if tasks are cooperative.

Otherwise, and only if you are sure that you won't be accumulating too many unresponsive tasks, each tying up a thread, you can still make use of TimeLimiter, as with the following utility method (just an example, not the only way to do it):
```java

/**
 * Wraps the given callable with a checked supplier that returns the wrapped callable's result if it completes
 * within the given timeout and returns the timeoutValue otherwise. Restores interrupt status and
 * returns timeoutValue if current thread is interrupted, and propagates exceptions thrown from callable.
 */
public static <T> CheckedSupplier<T> timeLimited(Duration timeout, T timeoutValue, Callable<T> callable) {
    return () -> {
	try {
	    return LIMITER.callWithTimeout(callable, timeout);
	} catch (TimeoutException ex) {
	    return timeoutValue;
	} catch (InterruptedException ex) {
	    Thread.currentThread().interrupt();
	    return timeoutValue;
	} catch (ExecutionException | UncheckedExecutionException ex) {
	    throw ex.getCause();
	}
    };
}

private static final TimeLimiter LIMITER = SimpleTimeLimiter.create(SCHEDULER);
```
This utility could be used to wrap your uncooperative tasks:
```java
boolean timedOut = Failsafe.with(retryPolicy)
    .with(SCHEDULER)
    .getAsync(timeLimited(timeout, true /* timed out */, () -> {
	log.info("executing");
	long startMillis = currentTimeMillis();
	do {
	    // loop for 2 seconds, not responsive to interruption
	} while (currentTimeMillis() - startMillis < 2_000);
	log.info("did not time out");
	return false;
    }))
    .get();
```
But this is risky: If, for example, the underlying task just opens up a network connection and waits for data, then repeatedly retrying this task under a time limit could silently take down a raft of threads and other system resources.

**Comment by Tembrel** [comment]
@jhalterman I think this can be closed.
