### ISSUE TITLE
Make RetryPolicy non final

### ISSUE THREAD

**Issue by MALPI** [jhalterman/failsafe#28]
I'd like to inherit from `RetryPolicy` to define default behaviours for certain usecases.

For example I'd like to create an `ApacheHttpRetryPolicy` which covers alreday the retry on the certain Apache exceptions.

This is not possible when the class is final and actually I don't really see a reason why it's done like that?

**Comment by jhalterman** [comment]
It's a good practice to mark classes as final unless they're specifically designed with inheritance in mind. In this case, I don't see a problem though I do have to ask, why not just create an instance of RetryPolicy that handles the exceptions you want and copy it if needed?

```
RetryPolicy basePolicy = new RetryPolicy().retryOn(apacheHttpExceptions);

public RetryPolicy newPolicy() {
  return basePolicy.copy();
}
```

**Comment by MALPI** [comment]
Because I want to use it in other Classes as well and with inheritance it is Mord convenient.

Besides that I'd like to give Circuitbreakers additional properties in Order to be able to identify them for monitoring reasons.

**Comment by jhalterman** [comment]
@MALPI Fair enough.

I've been asked about and have thought about having a CircuitBreaker registry or some sort of named tracking for CircuitBreakers, but for now I think that's best left to users to track circuit breakers however they want, via a Map or DI framework or whatever works best for them.

**Comment by MALPI** [comment]
Thanks a lot for your Quick response and your input! Really like failsafe so far!

**Comment by jhalterman** [comment]
@MALPI Thanks. If you like it, please spread the word :)

**Comment by MALPI** [comment]
Did so ;-) See twitter... will promoted it also in the company. ;-)

**Comment by MALPI** [comment]
Can you release a new version for that?

**Comment by jhalterman** [comment]
I have some other changes waiting to go in before a release, but hopefully after this weekend.

**Comment by jhalterman** [comment]
Released
