### ISSUE TITLE
Offer Spring endpoint for Circuit Breakers 

### ISSUE THREAD

**Issue by MALPI** [jhalterman/failsafe#30]
Hi @jhalterman,

as discussed yesterday already, I'd like to create an registry for the circuit breakers I created in order to gather information in which state they're.

These registry should then be exposed by an spring endpoint for monitoring purposes.

I hope you got that idea?

I am now thinking of to opensourcing it. Would you like to add it as a feature in this project, or should I setup a sepperate repo for it?

All the best

**Comment by MALPI** [comment]
See https://github.com/MALPI/failsafe-actuator

**Comment by theminecoder** [comment]
Would be best to make a separate repo for this so those who wish to use this project in a non spring context, like myself, still can. :)

**Comment by MALPI** [comment]
You could still have the src in the same repo but a different module/jar.

**Comment by jhalterman** [comment]
@MALPI This sort of thing is great, though as @theminecoder mentioned it's probably best as a separate repo.

**Comment by MALPI** [comment]
Ok, then I will keep it separate. Would you mind to link the project when it is in a Mord mature state?

**Comment by jhalterman** [comment]
@MALPI Sure. Drop me a line once you release it and we can start a wiki page for associated projects.

**Comment by MALPI** [comment]
@jhalterman I just released the first version http://bit.ly/2apcRrJ

**Comment by jhalterman** [comment]
@MALPI Good stuff :)

I just added a new wiki page for developers to post 3rd party tools and projects on and linked it from the README:

https://github.com/jhalterman/failsafe/wiki/3rd-Party-Tools
