### ISSUE TITLE
Add possibility for ErrorHandler

### ISSUE THREAD

**Issue by MALPI** [jhalterman/failsafe#31]
It would be nice to have the possibility to add an ErrorHandler to a Retrypolicy in order to avoid that a 'FailsafeException' is thrown. would be great to throw your self defined exceptions there.

Our current workaround is to wrap the Failsafe calls in try catch blocks and add the handling there, which produces redundant code snippets and makes it kind of ugly.

**Comment by jhalterman** [comment]
@MALPI I do plan to add support for fallbacks, which will allow you to perform some action when a failure error occurs and cannot be retried. See #17.

**Comment by MALPI** [comment]
@jhalterman not sure if this is the same. For sure having a fallback is also a good idea. But what I mean is, throwing custom Exceptions instead of the `FailsafeException`?

**Comment by jhalterman** [comment]
@MALPI Right now all synchronous exceptions are wrapped in `FailsafeException`. Are you suggesting that you'd like them to not be wrapped or that you'd like to be able to customize what exceptions are thrown?

The fallback capability in #17 will allow you to do whatever you want when a failure occurs, including throwing your own exception if you like.

**Comment by MALPI** [comment]
ok great!

**Comment by jhalterman** [comment]
@MALPI Just pushed this feature last night:

https://github.com/jhalterman/failsafe#fallbacks
