### ISSUE TITLE
Java 7 port

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [jhalterman/failsafe#43]
The library is quite cool, but given the lack of hard dependencies on Java 8 APIs the port could be quite simple.

This would help adopt it in Android environments, where we're currently pushing hard for RxJava. This could be a great stepstone.

**Comment by jhalterman** [comment]
@FranciscoE-Hudl Failsafe is written for Java 6+ :) I should probably find a way to make that more prominent. There are a few methods that depend on Java 8 classes (CompletableFuture stuff), but Java 6 users simply wouldn't use those and all is well.

Let me know if you're having any problems on Java 6/7.

**Comment by FranciscoE-Hudl** [comment]
Got it, I found the releaseCompileVersion vs devCompileVersion on the pom
