### ISSUE TITLE
Howto cancel async retries

### ISSUE THREAD

**Issue by leozilla** [jhalterman/failsafe#52]
Can you add a short example howto cancel async retries.

I was surprised that canceling the returned CompletableFuture does not cancel the retries.
Am I using the library wrong or is this intended?
How do I cancel the retry in the following example, do I need to add a canceled flag and check this in the future method?

```
scheduler = Executors.newScheduledThreadPool(1);
executor = Executors.newCachedThreadPool();

CompletableFuture<Proxy> proxyFuture = Failsafe.with(proxyRetryPolicy)
                       .with(scheduler)
                       .future(asyncExecution -> {
                           return CompletableFuture.supplyAsync(proxySupplier, executor);
                       });
					
// does not cancel the retry .. keeps retrying
proxyFuture.cancel(false);
proxyFuture.cancel(true);
```

**Comment by jhalterman** [comment]
@leozilla Just pushed a fix for this. This issue has to do with performing an execution on via `.future` specifically where the resulting `CompletableFuture` cancellation was not propagated to the associated `FailsafeFuture` which would stop continued execution. Maybe you can give this a try and let me know if it resolves your problem. I pushed a test case here:

https://github.com/jhalterman/failsafe/blob/732746b013bb93f3d3d29ac3f026af19ef3cc532/src/test/java/net/jodah/failsafe/issues/Issue52.java#L36-L59

**Comment by leozilla** [comment]
Ah, thanks!
I did not expect this to be a bug otherwise I would have tried to fix it myself.
Anyway I try your fix now and let you know how it worked out.

**Comment by jhalterman** [comment]
You should be able to just pull master and `mvn package` to give it a try. Tnx.

**Comment by jhalterman** [comment]
Going to close this now. @leozilla if this ends up not looking good on your end, feel free to re-open.

**Comment by jhalterman** [comment]
Released 0.9.3 with this fix.

**Comment by leozilla** [comment]
Sorry for the delay, it works for me.
Just one more minor thing. 
The test ExecutionTest#shouldSupportMaxDuration() breaks randomly on windows with oracle jdk 1.8.0_91
Reason seems to be the Thread.sleep is exactly as long as the max duration.

Fails
```
public void shouldSupportMaxDuration() throws Exception {
    Execution exec = new Execution(new RetryPolicy().withMaxDuration(100, TimeUnit.MILLISECONDS));
    assertTrue(exec.canRetryOn(e));
    assertTrue(exec.canRetryOn(e));
    Thread.sleep(100); // <--
    assertFalse(exec.canRetryOn(e));
    assertTrue(exec.isComplete());
  }
```

Succeeds (although still a little ugly)
```
public void shouldSupportMaxDuration() throws Exception {
    Execution exec = new Execution(new RetryPolicy().withMaxDuration(100, TimeUnit.MILLISECONDS));
    assertTrue(exec.canRetryOn(e));
    assertTrue(exec.canRetryOn(e));
    Thread.sleep(105); // <--
    assertFalse(exec.canRetryOn(e));
    assertTrue(exec.isComplete());
  }
```

Should I provide a fix/PR for it?

**Comment by jhalterman** [comment]
Yea, that would be a good change. PR welcome :)
