### ISSUE TITLE
Stability status.

### ISSUE THREAD

**Issue by hifall** [jhalterman/failsafe#54]
Hi, thanks for this awesome lib! The API looks quite interesting.

We'd like to use it in production. We have a couple of questions here: How stable is Failsafe? Is it used in production already?

**Comment by jhalterman** [comment]
Failsafe is stable and is used in production. A few places that are using it are noted [here](https://github.com/jhalterman/failsafe/wiki/Who's-Using-Failsafe). Hope that helps.

**Comment by hifall** [comment]
Yes, that does help. Thanks!

When is it planned to reach 1.0.0?

**Comment by jhalterman** [comment]
@hifall The current version number is pretty arbitrary. I'll probably bump it to 1.0 next time there's a significant feature addition or API change, but I don't have anything planned currently. In terms of stability, the current release series is GA/production ready :)
