### ISSUE TITLE
FailsafeFuture#complete is always calling fallback method

### ISSUE THREAD

**Issue by akincel** [jhalterman/failsafe#55]
`FailsafeFuture#complete:127
this.result = fallback.apply(result, failure);`

I think it's not right to always call fallback, even when no error occurred during processing. In that case `failure == null`, so workaround with checking if `failure == null` and then doing nothing in fallback is possible. But if feels weird.

What is your opinion on this?

**Comment by jhalterman** [comment]
This is a legit problem with async executions. Thanks for reporting.

**Comment by jhalterman** [comment]
Released 0.9.3 with this fix.
