### ISSUE TITLE
Not ABle to add Gradle dependency

### ISSUE THREAD

**Issue by vicky-fd** [jhalterman/failsafe#57]
I am not able to add gradle dependecy.
Added the following line to the build.gradle file
**compile 'net.jodah:failsafe:0.9.3'**

The Dependency that got included is **joda-time:2.9.4**

**Comment by jhalterman** [comment]
Is there a particular class where you're seeing a dependency on joda-time? I'm not seeing it.

**Comment by vicky-fd** [comment]
I want to use CircuitBreaker. I added up the dependency but could not import the class since the joda-time :2.9.4 jar does not contain CircuitBreaker class. Am I using it wrongly? If so, how to use a CircuitBreaker. In the Docs I could see you have just instantiated CircuitBreaker and worked with it.

Thanks,

**Comment by jhalterman** [comment]
You might check your gradle settings again. joda-time is unrelated to Failsafe. The proper dependency to import is [here](http://search.maven.org/#artifactdetails%7Cnet.jodah%7Cfailsafe%7C0.9.3%7C).
