### ISSUE TITLE
ExecutionTest#shouldSupportMaxDuration() breaks because of indeterministic scheduling

### ISSUE THREAD

**Issue by leozilla** [jhalterman/failsafe#58]
The test `ExecutionTest#shouldSupportMaxDuration()` breaks randomly on windows with oracle jdk 1.8.0_91
Reason seems to be the Thread.sleep is exactly as long as the max duration but it actually does not sleep for that long time.

Fails

```
public void shouldSupportMaxDuration() throws Exception {
    Execution exec = new Execution(new RetryPolicy().withMaxDuration(100, TimeUnit.MILLISECONDS));
    assertTrue(exec.canRetryOn(e));
    assertTrue(exec.canRetryOn(e));
    Thread.sleep(100); // <--
    assertFalse(exec.canRetryOn(e));
    assertTrue(exec.isComplete());
  }
```

Succeeds (although still a little ugly)

```
public void shouldSupportMaxDuration() throws Exception {
    Execution exec = new Execution(new RetryPolicy().withMaxDuration(100, TimeUnit.MILLISECONDS));
    assertTrue(exec.canRetryOn(e));
    assertTrue(exec.canRetryOn(e));
    Thread.sleep(105); // <--
    assertFalse(exec.canRetryOn(e));
    assertTrue(exec.isComplete());
  }
```

I suggest one of the following fixes:
1.  increase the Thread.sleep time, not a very elegant fix
2. abstract the time source by passing a clock in the constructor and use this to get current time, you can then control the time in your tests
3. use powermock or something to change the behaviour of the time source which is used. This does not require to modify the production code but makes the test code a little uglier.

Which one of the 3 suggestions do you prefer? or do you have another one?

**Comment by jhalterman** [comment]
I'm fine with open 1 for a few reasons: 

* It keeps the tests simple and easy to read, so someone browsing the code can easily understand what the test is trying to do.
* It's similar to what we're doing in various other tests (for better or worse, right now).

I'm open to improving things more substantially, but readability/simplicity of the tests is somewhat important.

**Comment by leozilla** [comment]
I am also fine with option 1. Just wanted to point out some possibilities.
A PR follows in the upcoming days.

**Comment by jhalterman** [comment]
Cool, thanks.

**Comment by jhalterman** [comment]
@leozilla I just went ahead and did this since I hadn't heard back from you :)
