### ISSUE TITLE
Execution Context Java 8 dependency

### ISSUE THREAD

**Issue by trevport** [jhalterman/failsafe#59]
Trying to do something like this in a Java 7 runtime environment:

```
    	 Failsafe.with(retryPolicy).get(new ContextualCallable<Response>() {
				@Override
				public Response call(ExecutionContext context) throws Exception {
					...
				}});	
```

Throws a class not found exception:

java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture

The following of course works fine:

```
    	 Failsafe.with(retryPolicy).get(new Callable<Response>() {
				@Override
				public Response call() throws Exception {
					...
				}});	
```

**Comment by sunng87** [comment]
This seems to be a change introduced in 0.9.3.

**Comment by jhalterman** [comment]
Apparently anonymous classes are loaded even if they're not referenced. That's what's happening [here](https://github.com/jhalterman/failsafe/blob/59ade146ab3c6c8d1f8cabb9e630e144f02c0e8d/src/main/java/net/jodah/failsafe/Functions.java#L268). Moving this logic to another file solves the problem. I need to verify there aren't any similar issues lurking where CompletableFuture is accidentally loaded when it shouldn't be.

**Comment by jhalterman** [comment]
0.9.5 was just released, which includes this fix.
