### ISSUE TITLE
CircuitBreaker.withFailureThreshold must be greater than RetryPolicy.withMaxRetries otherwise listeners not called

### ISSUE THREAD

**Issue by rashadmughal** [jhalterman/failsafe#60]
In class:
`net.jodah.failsafe.AbstractExecution`

line 114:

`boolean maxRetriesExceeded = retryPolicy.getMaxRetries() != -1 && executions > retryPolicy.getMaxRetries();`

Should be:
`boolean maxRetriesExceeded = retryPolicy.getMaxRetries() != -1 && executions >= retryPolicy.getMaxRetries();`

Otherwise if you set number failure threshold equal to max retry policy the listeners (onComplete, onFailure etc) are not executed.

**Comment by jhalterman** [comment]
@rashadmughal Do you have a failing test case that demonstrates this problem? The reason we say `executions > retryPolicy.getMaxRetries()` is because the first execution (execution #1) does not count as a retry.

**Comment by rashadmughal** [comment]
@jhalterman If that is the case which I thought might be once the tests started to fail, then I think there needs to be more validation.

In addition on a separate point, any exceptions by the listeners is simply swallowed up. Ideally they should at least log the error and move on.

**Comment by jhalterman** [comment]
@rashadmughal there is one test case that is flaky that needs to be improved, so i can understand your thinking.

Logging exceptions would require Failsafe to add a logging framework as a dependency, which I don't really want to do. Similar to the JDK's executor framework, it's up to you to add logging around the Runnable/Callable instances you submit. Alternatively, you can use the onFailedAttempt handler to log errors if you wish.
