### ISSUE TITLE
CircuiteBreaker and Jedis

### ISSUE THREAD

**Issue by vicky-fd** [jhalterman/failsafe#62]
I am not able to find how I could make use of CircuitBreaker with [Jedis](https://github.com/xetorthio/jedis) (A redis connection Helper).

CircuitBreaker can be implemented only on Runnable and Callable?
Can you provide me a way how I can make use of CircuitBreaker with JedisPool or Jedis which are Closeable.

**Comment by jhalterman** [comment]
You can wrap any code in a runnable or callable, including code that uses Jedis. I'm not a Jedis user so I can't help much there.
