### ISSUE TITLE
Logging of exceptions & count on which retry was performed

### ISSUE THREAD

**Issue by saikek** [jhalterman/failsafe#68]
My WebClient can throw a lot of exception types: `SSLException`, `SocketTimeoutException`, etc.
Is there a way how to log precisely what exception was thrown during retry block, or what caused to retry for future investigation?

```
return new RetryPolicy()
                .retryOn(IOException.class) 
                .retryIf(result -> result == null)
                .retryIf(result -> result.toString().isEmpty())
                .withDelay(delay, TimeUnit.SECONDS)
                .withMaxRetries(retry);
```

**Comment by sunng87** [comment]
There are listeners where you get register your logging code.

**Comment by saikek** [comment]
Are there any samples where i can take a look at ?

**Comment by jhalterman** [comment]
@saikek Have a look at the docs [here](https://github.com/jhalterman/failsafe#event-listeners).

To learn why an execution attempt failed, use the `onFailedAttempt` listener. The `onRetry` listener can also be used to learn when a retry is to be performed, and it is called immediately after `onFailedAttempt`:

```
Failsafe.with(retryPolicy)
  .onFailedAttempt(failure -> log.error("Connection attempt failed", failure))
  .onRetry((c, f, ctx) -> log.warn("Failure #{}. Retrying.", ctx.getExecutions()))
  .get(this::connect);
```

**Comment by saikek** [comment]
Thank you! 
It was obviously on README page but I did not see it.
