### ISSUE TITLE
CircuitBreaker Interface

### ISSUE THREAD

**Issue by jhaber** [jhalterman/failsafe#71]
I wanted to get your thoughts on converting `CircuitBreaker` to an interface. For some more context, I'm in the process of adding per-node circuit breakers to things like our Memcached client, but I want to allow users to control whether circuit breaking is enabled with a configuration flag. Rather than checking if circuit breaking is enabled throughout the code, I'd prefer to check once in the constructor and initialize the class with a no-op `CircuitBreaker` if disabled (one that always allows execution and ignores calls to records results). I can mostly achieve this by subclassing `CircuitBreaker`  and overriding methods, but it seems dirty and brittle. The other option is for me to make my own minimal circuit breaker interface with an impl that delegates to failsafe and another impl that does nothing (which is probably what I'll do for now), but I wanted to get your thoughts on whether this seems like a valid use-case.

**Comment by jhalterman** [comment]
Hi @jhaber 

I agree that subclassing and overriding is a bit brittle and the delegating approach is not ideal either. But if `CircuitBreaker` were an interface with noop methods, I don't think that would be much different than the subclassing approach - you would just have compilation errors if any method is added in the future.

I'm not opposed to `CircuitBreaker` being an interface, it just means an API change which is disruptive to other users/use cases for what, in this case, seems a small/marginal benefit for you, and probably not much of a benefit for other users.

Another solution that comes to mind, for me, is to pass your executable blocks through a single function that knows whether circuit breakers are enabled, and calls Failsafe from there (I'm not sure if you're using a `RetryPolicy` as well, so this code assumes no retries are needed):

```java
boolean circuitBreakerEnabled;
CircuitBreaker breaker = ....

public <T> T execute(Callable<T> callable) {
  return circuitBreakerEnabled ? Failsafe.with(breaker).get(callable) : callable.get();
}
```

**Comment by jhaber** [comment]
Thanks for the response and I think you bring up some good points. I ended up making my own interface with two implementations [here](https://github.com/HubSpot/java-memcached-client/blob/bc891d6630c4ef020fa7d4d951c72951a4dcde77/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L119-L162) and it wasn't too much of a hassle
