### ISSUE TITLE
CircuitBreaker policy should be separated from CircuitBreaker

### ISSUE THREAD

**Issue by testn** [jhalterman/failsafe#72]
It would be nice if the circuit breaker policy could be separated from CircuitBreaker class. This is analogous to FailSafe and RetryPolicy class.

**Comment by jhalterman** [comment]
like:

```CircuitBreaker breaker = new CircuitBreaker(new CircuitBreakerConfig()
    .withFailureThreshold(3, 10)
    .withSuccessThreshold(5));
Failsafe.with(breaker)....
```

?

I suppose they could be separate, but one of the use cases I wanted to support was being able to reconfigure (change the thresholds) a circuit breaker while it is in use.

**Comment by whiskeysierra** [comment]
> CircuitBreakerConfig

Please call it `CircuitBreakerPolicy`, if you decide to go forward with this.

> I wanted to support was being able to reconfigure (change the thresholds) a circuit breaker while it is in use

Fair enough. Could be done with the approach outlined in #99.

> Also the current API is a bit more streamlined which is nice.

True. I'd only prefer the move the listeners out of circuit breaker and either merge them with `Listeners` or at least register them on `A/SyncFailsafe` directly.
