### ISSUE TITLE
FailsafeException constructor shouldn't be only package accessible

### ISSUE THREAD

**Issue by MALPI** [jhalterman/failsafe#74]
Since `FailsafeException` constructor is only package accessible it's quite hard to write unit tests. 

Assume you have something like:

```
        try {
           return entity =
                    (Entity) Failsafe.with(getCircuitBreaker())
                            .with(getRetryPolicy)
                            .get(() -> {
                                return this.client.createEntity();
                            });
        } catch (final FailsafeException exception) {
            throw new GenericException(exception);
        }
```

If `client` is a mock you can easily force it `FailsafeException` when it's called. But this is only possible when the constructor is accessible.

**Comment by jhalterman** [comment]
I don't have any problem making those constructors public.

Unrelated, you can convert a `FailsafeException` to `GenericException` by using a fallback:

```
Failsafe.with(getCircuitBreaker())
  .with(getRetryPolicy)
  .get(() -> this.client.createEntity())
  .withFallback(exception -> { throw new GenericException(exception); });
```

**Comment by MALPI** [comment]
Tahnks for quick response. Is there already a plan for the next release?
