### ISSUE TITLE
AsyncExecution.completeOrRetry is not invoked when Error is thrown.

### ISSUE THREAD

**Issue by awallgren** [jhalterman/failsafe#76]
If async code throws AssertionError, OutOfMemoryError, or any other non-Exception Throwables, AsyncExecution.completeOrRetry is not invoked, which has some negative consequences:

1. It's not possible to use Failsafe in a testing context where AssertionError might be something you want to, for example, abort on.
2. It leaves things in an indeterminate state -- the FailsafeFuture never completes.

The solution would seem to be simple: catch Throwable instead of Exception where the exception is handed off to completeOrRetry. The changes seem confined only to the methods in Functions.

**Comment by awallgren** [comment]
Submitted pull request: https://github.com/jhalterman/failsafe/pull/77 (I'm sure there's a more elegant way to do it...)

**Comment by chhsiao90** [comment]
@awallgren - IMHO, I think ```Throwable``` or ```Error``` should not be catch.
In most case, when an error occurred, that implied the application was turned into some unexpected and fatal situation that was hard to recover.
If we try to recover from that situation, the application would result with an inconsistent and unknown state and will hard to evaluate what was happened.

What do you think!

**Comment by awallgren** [comment]
@chhsiao90 - I can think of use cases where it's quite legitimate to want to involve non-Exception Throwables (most likely Error and its descendants, but I've seen code extend Throwable instead of Exception), and don't agree that "most cases" imply application problems.

First, it seems that it's the intent of Failsafe is to support this:

1. This is how synchronous code in Failsafe works -- `SyncFailsafe.call` catches `Throwable` and calls `Execution.complete`. I see no reason why the async code should be different.
2. Most of the API uses `Throwable`, e.g. `RetryPolicy.abortOn` accepts `Class<? extends Throwable>`, not `Class<? extends Exception>`.

Some use cases:

1. What triggered the question on my part is that I want to run some async code as part of JUnit tests. I want to use `RetryPolicy.abortOn(AssertionError.class)` to capture any assertion from the async code but have it retry under other conditions.
2. Third party code sometimes extends `Throwable` instead of `Exception` in their checked exceptions (e.g. maven-core).
3. Some parts of the JDK do this as well -- for example, `java.util.zip.ZipError`
4. It seems quite legitimate to want to handle OutOfMemoryError and perhaps retry in a way that consumes less memory.

**Comment by chhsiao90** [comment]
@awallgren - Thanks your reply!
That was reasonable.
It's sound that there is still need the flexibility to let the user can handle with Throwable that was not extended Exception.
And if the sync version had the logic, then there is no reason to have different logic!

**Comment by jhalterman** [comment]
Hi @awallgren -

My intent with Failsafe, though maybe I didn't fully achieve this, was to favor the handling of Exceptions over Throwables (the various `net.jodah.failsafe.function` types throw `Exception` rather than `Throwable`) rather than Throwables or Errors since, as the [Error](https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html) docs mention, errors should not really be caught since an error represents something horrible having happened that can't reasonably be recovered from.

That said, handling `AssertionError` certainly sounds like a reasonable use case, at least for testing. I'm surprised to hear of Failsafe being used in testing, but hey, that's cool. Is that the only use case you have? Can you provide a little example or test that demonstrates how you're using it in this way?

> This is how synchronous code in Failsafe works -- SyncFailsafe.call catches Throwable and calls Execution.complete. I see no reason why the async code should be different.

This is a completely valid point, so I'd like to at least improve things in this way. But first, help me understand your use cases a bit more if you can...

**Comment by awallgren** [comment]
@jhalterman -- Thanks for the quick response.

It's true that the `Error` docs imply that `Error` should never be caught, though the wording is weaselly enough ("reasonable applications", "most such errors") that I would argue that's not a hard and fast rule in this context.

In addition, the facts on the ground are that existing code _does_ throw Error in cases where it's necessary/appropriate for the caller to catch it. For example, the JDK itself: `java.io.Console.readLine` catches `IOException` and rethrows it as `IOError`, presumably in a misguided attempt to avoid declaring `IOException` on `readLine` (surely the authors didn't intend that any application using that class should exit the thread/process rather than handle `Console` problems).

Also, this only covers `Error`, not other descendants of `Throwable`, as I mentioned above, with Maven and the JDK itself.

Further, the very nature of Failsafe is such that it's very handy for dealing with "exceptional" circumstances - though perhaps the appropriate word should be "throwable"...

As for my actual use cases, I have two off the top of my head:

1. I'm testing my own use of Failsafe around some async code that uses retries/circuit breakers and in this context I want `AssertionError` to cause an abort in Failsafe, so I configured the `RetryPolicy` to abort on `AssertionError`. When I wrote tests for this code, the abort never happens since the AssertionError is not caught, so the `FailsafeFuture` never completes.
2. In certain cases, we do want to catch `OutOfMemoryError` and retry (or at least recover with some contextually appropriate error). For example, some JDBC drivers (rhymes with Sporacle...) have a propensity to allocate large amounts of memory and it's possible for that to trigger OOME in large-scale very busy servers. Since the resulting OOME doesn't always happen on the thread that allocated the memory, we want to handle OOME, flag a low-memory condition in the process, and retry the code that received an OOME but wasn't really the cause of the problem.

That last one is a bit long, but is probably the more relevant one.

**Comment by jhalterman** [comment]
@awallgren I think your pull request did resolve this. I also added a few tests. Let me know if anything else related to this pops up.

**Comment by awallgren** [comment]
Thanks for adding the tests -- I should have done that myself before the pull request.

Keep up the good work -- I love dropping in useful libraries like this and deleting my own crufty code that tried to do the same thing, but  much less elegantly.

**Comment by jhalterman** [comment]
Thanks @awallgren. Feel free to spread the word about the project or give it a shoutout on Twitter or whatever :)

I just released 1.0.3 which includes this fix.
