### ISSUE TITLE
new RetryPolicy().retryOn(MyException.class) generates warning in IntelliJ

### ISSUE THREAD

**Issue by axelfontaine** [jhalterman/failsafe#81]
Warning: Unchecked generics array creation for varargs parameter

A non-varargs simple parameter overload would probably solve this.

**Comment by jhalterman** [comment]
I was originally thinking of doing @SafeVarargs at some point, but since Failsafe supports Java 6 right now (which doesn't ahve @SafeVarags) and @SafeVarargs requires the method be final anyways, this is a good alternative.

**Comment by jhalterman** [comment]
This has been released in 1.0.4.
