### ISSUE TITLE
Users mailing list

### ISSUE THREAD

**Issue by MALPI** [jhalterman/failsafe#82]
Hi,

is it possible to create a users mailing list in order to share information about updates and ask questions?

For example I was waiting for this jittering feature but only found out about it by incidently re-checking the project.

Furthermore it would be great to create a "how to contribute" section in the readme.

**Comment by jhalterman** [comment]
A CONTRIBUTING guide is definitely warranted. As for announcing releases on a mailing list, I'm not sure if it's worth the effort. All of the releases are posted to github though, along with changes to the CHANGES.md file, and there are various ways of watching for project releases on Github, such as this:

http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases

I wish there was a more official way, but a bit of googling shows a lot of different approaches.

**Comment by reisenberger** [comment]
You can also subscribe to releases (across many different release platforms/programming languages) through library tracking websites, such as: [libraries.io](https://libraries.io/maven/net.jodah:failsafe)

**Comment by MALPI** [comment]
librarios.io seems to be feasible, thanks a lot.
