### ISSUE TITLE
Prevent duplicate executions

### ISSUE THREAD

**Issue by arun-ram** [jhalterman/failsafe#83]
I am looking for a way to use FailSafe to process items in a queue where items are constantly added by a thread. When a new item is added to the queue, I want to invoke processItem() using fail safe so that the processing is retried according to a retry policy. When another item is added but the processing is currently happening, I don't want to invoke processItem() until the previous one has completed. Does FailSafe support this use case?

Here is the code:

```
public class RequestProcessor {
    private Queue<Object> queue;

    public addItemToQueue(Object item) {
        queue.put(item);
        newItemAddedToQueue();
    }

    public void newItemAddedToQueue() {
        RetryPolicy retryPolicy = new RetryPolicy()
                .withBackoff(1, 3, TimeUnit.MINUTES)
                .withMaxRetries(-1);
        Failsafe.with(retryPolicy)
                .with(new ScheduledThreadPoolExecutor(1))
                .run(this::processRequest);
    }

    protected void processRequest() throws IOException {
        while (Object item = queue.peek() != null){
            processItem(item);
        }
    }
}

```

**Comment by jhalterman** [comment]
> Does FailSafe support this use case?

Sure, Failsafe can support pretty much any type of execution since it's basically just a wrapper around your executable logic.

I'm not sure if your code is just an example of if it's real, but you might want to use `queue.poll()` instead of `peek` since items will never be removed from the queue in this example. You also might want to create a single `ScheduledThreadPoolExecutor` to reuse rather than one for each item.

If I understand your use case, another approach would be to use a `BlockingQueue`, where a single thread/ExecutorService loops and calls `poll` on the BlockingQueue:

```
ExecutoService consumerExecutor = Executors.newSingleThreadExecutor();

public addItemToQueue(Object item) {
   queue.put(item);
}

public void consumeFromQueue() {
  consumerExecutor.submit(() -> {
    while (true) {
      Object item = queue.take();
      Failsafe.with(retryPolicy).run(() -> processItem(item));
    }
  });
}
```

**Comment by arun-ram** [comment]
Thanks very much for you quick response. The code I posted was a simplified version of the real code (the ScheduledThreadPoolExecutor was created only once externally and passed in). Also, the queue in my case may/may not be a blocking queue (since that is also passed in).
I was able to use your solution. Your solution did solve my problem by getting rid of the call to setup a Failsafe execution whenever a new item was added to the queue. Instead, I could setup a thread (consumerExecutor) that ran independently and processed one item at a time. 
What I had not realized earlier was that you could setup a synchronous failsafe execution by just not providing a ScheduledExecutorService. I was under the impression that Failsafe was always asynchronous. Perhaps you could mention this in the Failsafe class javadoc.
Thanks again.
