### ISSUE TITLE
`AsyncFailsafe#future(...)` should `completeExceptionally(...)` not raise

### ISSUE THREAD

**Issue by brianm** [jhalterman/failsafe#84]
If the circuit is open, I expect the `CompletableFuture` returned by `AsyncFailsafe#future(...)` to be already completed with the circuit open, rather than have the `future` method raise an exception.

A common case of CF oriented APIs is combing them for fan-out type behavior, particularly in the case where they are being used with a circuit breaker. In that case, the failure handling is usually baked into the CF graph, NOT in the construction of the CF graph.

**Comment by jhalterman** [comment]
Hi Brian,

You are right - the [current behavior](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/AsyncFailsafe.html#future-java.util.concurrent.Callable-) is to immediately throw `CircuitBreakerOpenException` on any type of execution attempt, sync or async, if the configured breaker is open. Your point about this messing with the ability to chain CompletableFutures is valid though.

Just to make sure I understand your scenario, do you mind sharing an example?

**Comment by jhalterman** [comment]
@brianm Let me know if this change does or doesn't address your issue. See [this test](https://github.com/jhalterman/failsafe/blob/6cc7e1368d5d177229d0b1e42a95ed6bd640bc28/src/test/java/net/jodah/failsafe/issues/Issue84.java#L41-L42) in particular.

**Comment by jhalterman** [comment]
This has been released in 1.0.4.

**Comment by brianm** [comment]
Fabulous, thank you!
