### ISSUE TITLE
suppresses exceptions of type ClassNotFoundException

### ISSUE THREAD

**Issue by pravsingh** [jhalterman/failsafe#86]
I have a situation where response returned after Restful call includes a breaking change. Due to this call to SyncFailsafe.get fails silently (I had fallback setup).
After debugging for sometime, I noticed that SyncFailsafe.fallbackFor ignores the exception message. 

In case of exception being other than FailsafeException, should we log it so that we don't miss it out?

```java
class SyncFailsafe .. {
...

private <T> T call(Callable<T> callable) {
...
if (fallback != null)
          return fallbackFor((R) result, failure);
 throw failure instanceof FailsafeException ? (FailsafeException) failure : new FailsafeException(failure);
....
}
...
  @SuppressWarnings("unchecked")
  private <T> T fallbackFor(R result, Throwable failure) {
    try {
      return (T) fallback.apply(result, failure);
    } catch (Exception e) {
      throw e instanceof FailsafeException ? (FailsafeException) e : new FailsafeException(e);
    }
  }
```

Looking at the code, its obvious that the exception suppression happens when fallback doesn't throw any exception.

**Comment by jhalterman** [comment]
That's right. It's up to the fallback implementation to decide how to handle the exception. This is the intended behavior and follows precedent set by other "Try" monad implementations elsewhere, such as [Scala's](http://www.scala-lang.org/api/2.9.3/scala/util/Try.html).

You might look at using one of the `withFallback` methods that takes a function, so you can choose to re-throw any exception if you want:

http://jodah.net/failsafe/javadoc/net/jodah/failsafe/FailsafeConfig.html#withFallback-net.jodah.failsafe.function.CheckedConsumer-

**Comment by pravsingh** [comment]
Thank you for your prompt response.

Noticed that the Consumer you suggested doesn't get Throwable.

Only CheckedBiConsumer (as below code from Functions.java) receives Throwable:

```java
static <T, U, R> CheckedBiFunction<T, U, R> fnOf(final CheckedBiConsumer<T, U> consumer) {
    return new CheckedBiFunction<T, U, R>() {
      @Override
      public R apply(T t, U u) throws Exception {
        consumer.accept(t, u);
        return null;
      }
    };
  }
```

Do you recommend using CheckedBiConsumer in case I need to receive exception?

**Comment by jhalterman** [comment]
I'm not sure what you mean by not getting Throwable. There are several `withFallback` methods that can handle a Throwable, and any of them should work for you.

**Comment by pravsingh** [comment]
"consumer.accept(t, u);" is really passing back the 't' param whereas other fnOf variants don't do that. I might be wrong but this is what I got and it solves my problem.

thank you @jhalterman for your prompt response. I'll close the issue.
