### ISSUE TITLE
[DISCUSS] RetryPolicy should be harder to use wrong

### ISSUE THREAD

**Issue by davidmankin** [jhalterman/failsafe#87]
I suspect most people want their retry policies to eventually complete.  In my service we got burned because we used a retry policy without a `maxRetries` or `maxDuration`, so a bad call was tried over and over indefinitely.  (We mistakenly thought a `maxDelay` would imply a retry termination criteria.)

I propose that the API for RetryPolicy be changed such that a Retry policy cannot be used without specifying one of

- `setMaxDuration()`
- `setMaxRetries()`
- `setUnlimitedRetries()`   // New method which would reset `maxDuration` and `maxRetries`

This would require the user to explicitly choose whether they want a policy that must terminate or one that may not, while not losing the current unlimited retries capabilities.

One of my driving API design principles is "make it hard to do the wrong thing" (while still being designed to be as easy to use as possible).  Today, I think the API makes it too easy to do the wrong thing (i.e. unexpected infinite loop).

**Comment by jhalterman** [comment]
Hi David,

You are right that right now, by default, `new RetryPolicy()` will retry forever unless a max retries or duration are specified. I'm open to changing this behavior, but it could/would be a breaking change for some users, so I'd be interested to get more feedback on whether this is a good thing. I'm also interested to see what precedent there is in other similar technologies libraries around this issue (FWIW).

Your principle makes sense. The current behavior is based on wanting to make the API as simple as possible, where performing retries is as simple as using a `new RetryPolicy()` and where additional constraints can be added from there.

**Comment by jhalterman** [comment]
This could also apply to `CircuitBreaker`, which by default, has no delay, and therefore transitions from open to half-open on the next execution attempt.

**Comment by reisenberger** [comment]
>what precedent there is in other similar technologies/libraries around this issue (FWIW).

FWIW, in [Polly for .NET](https://github.com/App-vNext/Polly/), we avoid providing invisible defaults for key dimensions: we force users to provide key config explicitly when constructing a Policy.  Where there isn't an _obvious_/dominant-choice default, I prefer users to have to think about what they want, than provide a default which they may unthinkably fall back on, and which may not suit all.  Avoiding invisible defaults also makes the calling code less opaque to subsequent devs who come along, and may not know the library.  

We don't operate however with Failsafe's (lovely) [syntax which allows a no-args ctor followed by postfix, accumulating configuration](https://github.com/jhalterman/failsafe#usage).  The huge disadvantage with Polly's configure-everything-in-one-shot approach (which I inherited on the project) is [burgeoning numbers of overloads](https://github.com/App-vNext/Polly#wait-and-retry), and [richest overloads with lots of parameters](https://github.com/App-vNext/Polly/blob/e9269ad9d24b9e0bd0cde546343d0c4d1539b77c/src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerSyntax.cs#L190).  I love Failsafe's syntax, to the extend that we've [considered converting Polly to it](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#extend-fluent-syntax-to-reduce-the-number-of-overloads).  If I was starting Polly again ... ... best compromise might be a syntax which forces key dimensions explicit, but allows optionals to be added by accumulation.

**Comment by jhalterman** [comment]
Heading into 2.0 as we are, now would be the time to change the default (no arg) behavior of a RetryPolicy. Any suggestions on what the defaults should be?

My own thought: 1 retry, and keep the current delay default of 0 (no delay).

Other thoughts?

**Comment by jhalterman** [comment]
The new default maxAttempts is 3, with no delay. This will not be correct for most users, but at least hopefully it won't be damaging.
