### ISSUE TITLE
retryIf when maxretries == actual number of retries

### ISSUE THREAD

**Issue by jbndbc** [jhalterman/failsafe#88]
Hi

I have a RetryPolicy like this:

    final RetryPolicy RETRY_POLICY = new RetryPolicy()
            .retryOn(Collections.singletonList(ProcessingException.class))
            .retryIf((Response response) -> {
                       final boolean retry =   response.getStatus() == 404;
                       if (retry) {
                           response.close();
                       }
                       return retry;
            })
            .withDelay(1, TimeUnit.SECONDS)
            .withMaxRetries(10);

I have to close the response (Jersey) to avoid leaking connections, but the client code in this particular application would like to access the response entity even for a 404 response, which isn't possible since the response is already closed.

Is it possible for FailSafe to not execute retryIf on the last allowed iteration where maxretries == actual number of retries, since the boolean return value of this call doesn't really matter.

**Comment by jhalterman** [comment]
I think this is a reasonable enhancement. 

Implementation note: If `RetryPolicy.allowsRetries` is false, then don't bother invoking `RetryPolicy.canRetryFor`.

**Comment by jhalterman** [comment]
I just recalled why this is problematic: we use the `RetryPolicy` methods to not only determine if a retry should be performed, but based on that, whether the execution was a success or not. If a retry *should* be performed but we've hit the max retries, we will not retry again but will mark the execution as a failure and call the `onFailure` event handlers.

For your situation, it's probably best to keep the `retryIf` implementation simple and idempotent:

```
  .retryIf((Response response) -> return response.getStatus() == 404)
```

And to close the response from within an [event listener](https://github.com/jhalterman/failsafe#event-listeners):

```
onRetry((connection, failure) -> connection.close);
```

`onRetry` is only called before a retry attempt, which unlike `onFailedAttempt`, means it's not called after the last failure. Hope that helps...

**Comment by jbndbc** [comment]
onRetry() did the trick. Thanks for the quick reply.
