### ISSUE TITLE
Struggling with a combination of retry and circuit-breaker together

### ISSUE THREAD

**Issue by gochs1** [jhalterman/failsafe#90]
Hello,

I am trying the following scenario:
I have an outbound rest client call which I want to retry for certain exceptions and max 5 times with increasing wait times. In addition I want to have a circuit breaker configuration which would  check for certain exceptions and amount of failures.
Questions:
* How does retry and circuit breaker interact if both policies are specified?
* Can I define a policy for circuit breaker which counts a certain amount of retries as an event which opens the circuit breaker?
* Is there an example available which combines both ( retry and circuit breaker)?
* If I call my rest client via failsave when the circuit breaker is open it executes it. I expected an error?

Thanks in advance for your help.

**Comment by whiskeysierra** [comment]
> How does retry and circuit breaker interact if both policies are specified?

Retries are counted as failures for the circuit breaker. Docs are currently incorrect. See #96 and #119.

> Can I define a policy for circuit breaker which counts a certain amount of retries as an event which opens the circuit breaker?

Retries are indistinguishable from normal execution, I believe. So no. 

> Is there an example available which combines both ( retry and circuit breaker)?

https://github.com/jhalterman/failsafe#with-retries Is a bit short, but shows the general idea. You should just try it out in a small unit test.

> If I call my rest client via failsave when the circuit breaker is open it executes it. I expected an error?

Yes, that's the general idea. If the circuit breaker is open it signals to your application that the remote service has a temporary (?) issue right now and it's not even worth trying until the circuit goes back to half-open and then closed.

**Comment by jhalterman** [comment]
Proper support for composable Policies was merged via 5d919d5fe5725040b4117c85fba2bc4a4dacdbc9. This should be release soon as part of 2.0. 

To answer some questions in this isue for posterity:

> How does retry and circuit breaker interact if both policies are specified?

If they are supplied separately (`Failsafe.with(retryPolicy).with(circuitBreaker)...`, then Failsafe uses a _logical_ ordering where the circuitBreaker handles execution results first, then the retryPolicy, then any configured fallback. Failsafe 2 will allow policies to be configured in any order, including multiple policies of the same type, via: `Failsafe.with(fallback, retryPolicy, circuitBreaker)` where the last policy specified handles a result first (the docs for 2.0 will explain the rationale behind this).
