### ISSUE TITLE
OSGi-fy the library

### ISSUE THREAD

**Issue by amitjoy** [jhalterman/failsafe#91]
It would be better off to have it as an OSGi bundle so that it can be used in modular OSGi containers.

**Comment by jhalterman** [comment]
Hi @amitjoy - I'm not an OSGi user, but there was some work contributed to OSGi'ify (sp?) the library previously. Is it coming up short in some way? Any details or improvements you might contribute?

**Comment by amitjoy** [comment]
I am just thinking to enhance this library a bit so that it works in OSGi and non-OSGi environment both. I thought it would be better off to use this library in other projects as well. It won't be difficult to make it OSGi ready. I will try to make a PR soon to OSGi-fy this library.

**Comment by jhalterman** [comment]
My comment above was that the library already is OSGi ready AFAIK. The [bundle plugin](https://github.com/jhalterman/failsafe/blob/master/pom.xml#L111-L139) adds a manifest to the release'd jars...

**Comment by amitjoy** [comment]
I didn't notice that previously. Just had a look at the released version 1.0.4 from maven. It looks the manifest is not correct. Lots of potential problems exists. I will try to clean up the bundle plugin.

**Comment by jhalterman** [comment]
Sounds good 👍
