### ISSUE TITLE
RetryPolicy & CircuitBreaker

### ISSUE THREAD

**Issue by driesva** [jhalterman/failsafe#96]
In the [documentation](https://github.com/jhalterman/failsafe#with-retries) there's written:

_Execution failures are first retried according to the RetryPolicy, then if the policy is exceeded the failure is recorded by the CircuitBreaker._

But it turns out the retry failures are always recorded by the circuit breaker... When looking at the source code in _AbstractExecution::complete_ it seems to confirm this. Either the documentation is wrong or the code is not behaving correctly.

**Comment by celdridge91190** [comment]
I'm having the same issue. My CircuitBreaker is tripping on the first failure attempt, even though my RetryPolicy indicates it should retry. I added logging statements and noticed my Breaker was closed before I even entered my retryOn method.

**Comment by jhalterman** [comment]
Proper support for composable Policies was merged via 5d919d5fe5725040b4117c85fba2bc4a4dacdbc9. This should be release soon.

**Comment by celdridge91190** [comment]
Do you happen to know when 2.0 is scheduled to be released?

**Comment by jhalterman** [comment]
@celdridge91190 There are a couple of remaining things I'd like to sort out (see #159 for more info), but probably within a week or two.
