### ISSUE TITLE
Retry with backoff

### ISSUE THREAD

**Issue by driesva** [jhalterman/failsafe#97]
Imagine we have following retry policy

` RetryPolicy retryPolicy = new RetryPolicy()
                .withBackoff(5, 30, TimeUnit.SECONDS)
                .withMaxRetries(3);`

I assumed that the first retry was after 5 secs, being the initial delay. It turns out it's after 10 seconds. So the default delay factor of 2 already kicks in with the first delay. 

Is this intentionally or an issue?

**Comment by jhalterman** [comment]
This looks like an issue. Thanks for reporting!
