### ISSUE TITLE
Take suppliers so that the config can be live-reloaded

### ISSUE THREAD

**Issue by ghost** [jhalterman/failsafe#99]
I have an application that does live config reloading, and has a failsafe loop. If the config governing the loop changes, I have to halt the current loop and restart it with the new config. If there were methods that took in suppliers, this would not be necessary.

Happy to contribute this if it's agreed that it is a good idea.

**Comment by jnewman2501** [comment]
@jhalterman - thoughts?

**Comment by jhalterman** [comment]
So you were thinking a supplier that received a `RetryPolicy` or `CircuitBreaker`? Since Failsafe is invoked statically, you could just supply a new `RetryPolicy` or `CircuitBreaker` the next time you use it.

**Comment by jnewman2501** [comment]
Not quite. I have a loop that looks like this:

```
FailSafe.with(retryPolicy, circuitBreaker)
   .run(() -> {
    acquireLock();
    while(shouldContinue) {
      doWork();
    }
  });
```

While the loop is doing work, the config could reload, and I'd like to have the RetryPolicy/CircuitBreaker change dynamically without having to stop the loop and re-instantiate my Failsafe.

**Comment by jhalterman** [comment]
Can you tell me more about your use case - what kinds of changes to retry policy or circuit breaker you want to make while the Failsafe execution is taking place?

**Comment by jnewman2501** [comment]
Just changing the minimum and maximum timeout for the retry policy. So basically all places that take an duration would also be able to take suppliers.

**Comment by jhalterman** [comment]
Is it not workable to move the loop outside of the Failsafe call?

**Comment by jnewman2501** [comment]
The idea is that the lock needs to be acquired, which involves network IO, and when we break out of the work loop we'll need to acquire the lock.

If you don't think this is something the lib should support happy to close out and make it work as necessary in our upstream code :)

**Comment by jhalterman** [comment]
Revisiting this after a while: 

Would it make sense to simply be able to modify a RetryPolicy on the fly? This would fall under #47.

**Comment by jhalterman** [comment]
Since this has been sitting a while, closing in favor of #47.
